-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:48
CoD.PlayerInspection_InfoPaneWinStreak = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.PlayerInspection_InfoPaneWinStreak.__defaultWidth = 348 --[[ @ 0]]
CoD.PlayerInspection_InfoPaneWinStreak.__defaultHeight = 33 --[[ @ 0]]
CoD.PlayerInspection_InfoPaneWinStreak.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIHorizontalList.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9, 10, true ) --[[ @ 0]]
	self:setAlignment( LUI.Alignment.Center ) --[[ @ 0]]
	self:setClass( CoD.PlayerInspection_InfoPaneWinStreak ) --[[ @ 0]]
	self.id = "PlayerInspection_InfoPaneWinStreak" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local Background = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	Background:setRGB( 0, 0, 0 ) --[[ @ 0]]
	Background:setAlpha( 0.4 ) --[[ @ 0]]
	self:addElement( Background ) --[[ @ 0]]
	self.Background = Background --[[ @ 0]]
	
	local WinStreakTitle = LUI.UIText.new( 0, 0, 51.5, 244.5, 0.5, 0.5, -9, 8 ) --[[ @ 0]]
	WinStreakTitle:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	WinStreakTitle:setText( LocalizeToUpperString( @"hash_2106B091E85DC369" ) ) --[[ @ 0]]
	WinStreakTitle:setTTF( "ttmussels_regular" ) --[[ @ 0]]
	WinStreakTitle:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_90D57B1E92D39D7" ) ) --[[ @ 0]]
	WinStreakTitle:setShaderVector( 0, 1, 0, 0, 0 ) --[[ @ 0]]
	WinStreakTitle:setShaderVector( 1, 0, 0, 0, 0 ) --[[ @ 0]]
	WinStreakTitle:setShaderVector( 2, 0, 0, 0, 0 ) --[[ @ 0]]
	WinStreakTitle:setLetterSpacing( 1 ) --[[ @ 0]]
	WinStreakTitle:setLineSpacing( 1 ) --[[ @ 0]]
	WinStreakTitle:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
	self:addElement( WinStreakTitle ) --[[ @ 0]]
	self.WinStreakTitle = WinStreakTitle --[[ @ 0]]
	
	local WinStreak = LUI.UIText.new( 0, 0, 254.5, 296.5, 0, 0, 0, 33 ) --[[ @ 0]]
	WinStreak:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b ) --[[ @ 0]]
	WinStreak:setTTF( "0arame_mono_stencil" ) --[[ @ 0]]
	WinStreak:setAlignment( Enum[@"luialignment"][@"lui_alignment_center"] ) --[[ @ 0]]
	WinStreak:linkToElementModel( self, "arenaWinStreak", true, function ( model )
		local f2_local0 = model:get() --[[ @ 0]]
		if f2_local0 ~= nil then
			WinStreak:setText( f2_local0 ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( WinStreak ) --[[ @ 0]]
	self.WinStreak = WinStreak --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "Invisible",
			condition = function ( menu, element, event )
				return not CoD.RankUtility.IsCurrentRankModeEqualTo( CoD.RankUtility.RankMode.Arena )
			end
		},
		{
			stateName = "AsianLanguage",
			condition = function ( menu, element, event )
				return CoD.BaseUtility.IsCurrentLanguageAsian()
			end
		}
	} ) --[[ @ 0]]
	local f1_local4 = self --[[ @ 0]]
	local f1_local5 = self.subscribeToModel --[[ @ 0]]
	local f1_local6 = Engine[@"getglobalmodel"]() --[[ @ 0]]
	f1_local5( f1_local4, f1_local6["lobbyRoot.rankMode"], function ( f5_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f5_arg0:get(),
			modelName = "lobbyRoot.rankMode"
		} ) --[[ @ 0]]
	end, false ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.PlayerInspection_InfoPaneWinStreak.__resetProperties = function ( f6_arg0 )
	f6_arg0.WinStreakTitle:completeAnimation() --[[ @ 0]]
	f6_arg0.Background:completeAnimation() --[[ @ 0]]
	f6_arg0.WinStreak:completeAnimation() --[[ @ 0]]
	f6_arg0.WinStreakTitle:setTopBottom( 0.5, 0.5, -9, 8 ) --[[ @ 0]]
	f6_arg0.WinStreakTitle:setAlpha( 1 ) --[[ @ 0]]
	f6_arg0.Background:setAlpha( 0.4 ) --[[ @ 0]]
	f6_arg0.WinStreak:setAlpha( 1 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.PlayerInspection_InfoPaneWinStreak.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	Invisible = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties() --[[ @ 0]]
			f8_arg0:setupElementClipCounter( 3 ) --[[ @ 0]]
			f8_arg0.Background:completeAnimation() --[[ @ 0]]
			f8_arg0.Background:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.clipFinished( f8_arg0.Background ) --[[ @ 0]]
			f8_arg0.WinStreakTitle:completeAnimation() --[[ @ 0]]
			f8_arg0.WinStreakTitle:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.clipFinished( f8_arg0.WinStreakTitle ) --[[ @ 0]]
			f8_arg0.WinStreak:completeAnimation() --[[ @ 0]]
			f8_arg0.WinStreak:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.clipFinished( f8_arg0.WinStreak ) --[[ @ 0]]
		end
	},
	AsianLanguage = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties() --[[ @ 0]]
			f9_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f9_arg0.WinStreakTitle:completeAnimation() --[[ @ 0]]
			f9_arg0.WinStreakTitle:setTopBottom( 0.5, 0.5, -4, 10 ) --[[ @ 0]]
			f9_arg0.clipFinished( f9_arg0.WinStreakTitle ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.PlayerInspection_InfoPaneWinStreak.__onClose = function ( f10_arg0 )
	f10_arg0.WinStreak:close() --[[ @ 0]]
end
 --[[ @ 0]]
