-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:48
CoD.WarzoneDpadButton = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.WarzoneDpadButton.__defaultWidth = 64 --[[ @ 0]]
CoD.WarzoneDpadButton.__defaultHeight = 64 --[[ @ 0]]
CoD.WarzoneDpadButton.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.WarzoneDpadButton ) --[[ @ 0]]
	self.id = "WarzoneDpadButton" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local downImage = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	downImage:setAlpha( 0 ) --[[ @ 0]]
	downImage:setMaterial( LUI.UIImage.GetCachedMaterial( @"uie_wipe_delta_normal" ) ) --[[ @ 0]]
	downImage:setShaderVector( 0, 0.33, 0.67, 0, 0 ) --[[ @ 0]]
	downImage:setShaderVector( 1, 0, 0, 0, 0 ) --[[ @ 0]]
	downImage:setShaderVector( 2, 0, 0.4, 0, 0 ) --[[ @ 0]]
	downImage:setShaderVector( 3, 0, 0, 0, 0 ) --[[ @ 0]]
	downImage:setShaderVector( 4, 0, 0, 0, 0 ) --[[ @ 0]]
	downImage:subscribeToGlobalModel( f1_arg1, "Controller", "dpad_up_button_image", function ( model )
		local f2_local0 = model:get() --[[ @ 0]]
		if f2_local0 ~= nil then
			downImage:setImage( RegisterImage( f2_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( downImage ) --[[ @ 0]]
	self.downImage = downImage --[[ @ 0]]
	
	local downImage2 = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	downImage2:setImage( RegisterImage( @"uie_ui_hud_wz_hud_core_qe_dpad_up" ) ) --[[ @ 0]]
	self:addElement( downImage2 ) --[[ @ 0]]
	self.downImage2 = downImage2 --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "Visible",
			condition = function ( menu, element, event )
				return true
			end
		},
		{
			stateName = "VisibleForCallout",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		}
	} ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.WarzoneDpadButton.__resetProperties = function ( f5_arg0 )
	f5_arg0.downImage:completeAnimation() --[[ @ 0]]
	f5_arg0.downImage2:completeAnimation() --[[ @ 0]]
	f5_arg0.downImage:setAlpha( 0 ) --[[ @ 0]]
	f5_arg0.downImage2:setAlpha( 1 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.WarzoneDpadButton.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties() --[[ @ 0]]
			f6_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f6_arg0.downImage:completeAnimation() --[[ @ 0]]
			f6_arg0.downImage:setAlpha( 0 ) --[[ @ 0]]
			f6_arg0.clipFinished( f6_arg0.downImage ) --[[ @ 0]]
			f6_arg0.downImage2:completeAnimation() --[[ @ 0]]
			f6_arg0.downImage2:setAlpha( 0 ) --[[ @ 0]]
			f6_arg0.clipFinished( f6_arg0.downImage2 ) --[[ @ 0]]
		end
	},
	Visible = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f7_arg0.downImage:completeAnimation() --[[ @ 0]]
			f7_arg0.downImage:setAlpha( 0 ) --[[ @ 0]]
			f7_arg0.clipFinished( f7_arg0.downImage ) --[[ @ 0]]
		end
	},
	VisibleForCallout = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties() --[[ @ 0]]
			f8_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f8_arg0.downImage:completeAnimation() --[[ @ 0]]
			f8_arg0.downImage:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.clipFinished( f8_arg0.downImage ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.WarzoneDpadButton.__onClose = function ( f9_arg0 )
	f9_arg0.downImage:close() --[[ @ 0]]
end
 --[[ @ 0]]
