-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:48
CoD.CompassGroupMPSmoke = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.CompassGroupMPSmoke.__defaultWidth = 424 --[[ @ 0]]
CoD.CompassGroupMPSmoke.__defaultHeight = 424 --[[ @ 0]]
CoD.CompassGroupMPSmoke.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.CompassGroupMPSmoke ) --[[ @ 0]]
	self.id = "CompassGroupMPSmoke" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local smokeGrenadeEffect = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	smokeGrenadeEffect:setMaterial( LUI.UIImage.GetCachedMaterial( @"uie_smoke" ) ) --[[ @ 0]]
	smokeGrenadeEffect:subscribeToGlobalModel( f1_arg1, "HUDItems", "smokeEffect", function ( model )
		local f2_local0 = model:get() --[[ @ 0]]
		if f2_local0 ~= nil then
			smokeGrenadeEffect:setShaderVector( 0, CoD.GetVectorComponentFromString( f2_local0, 1 ), CoD.GetVectorComponentFromString( f2_local0, 2 ), CoD.GetVectorComponentFromString( f2_local0, 3 ), CoD.GetVectorComponentFromString( f2_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( smokeGrenadeEffect ) --[[ @ 0]]
	self.smokeGrenadeEffect = smokeGrenadeEffect --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "Visible",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsGlobalDataSourceModelValueGreaterThan( f1_arg1, "HUDItems", "smokeEffect", 0 )
			end
		}
	} ) --[[ @ 0]]
	local f1_local2 = self --[[ @ 0]]
	local f1_local3 = self.subscribeToModel --[[ @ 0]]
	local f1_local4 = DataSources.HUDItems.getModel( f1_arg1 ) --[[ @ 0]]
	f1_local3( f1_local2, f1_local4.smokeEffect, function ( f4_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f4_arg0:get(),
			modelName = "smokeEffect"
		} ) --[[ @ 0]]
	end, false ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.CompassGroupMPSmoke.__resetProperties = function ( f5_arg0 )
	f5_arg0.smokeGrenadeEffect:completeAnimation() --[[ @ 0]]
	f5_arg0.smokeGrenadeEffect:setAlpha( 1 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.CompassGroupMPSmoke.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties() --[[ @ 0]]
			f6_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f6_arg0.smokeGrenadeEffect:completeAnimation() --[[ @ 0]]
			f6_arg0.smokeGrenadeEffect:setAlpha( 0 ) --[[ @ 0]]
			f6_arg0.clipFinished( f6_arg0.smokeGrenadeEffect ) --[[ @ 0]]
		end
	},
	Visible = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.CompassGroupMPSmoke.__onClose = function ( f8_arg0 )
	f8_arg0.smokeGrenadeEffect:close() --[[ @ 0]]
end
 --[[ @ 0]]
