-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:32
CoD.AARGametypeHeader = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.AARGametypeHeader.__defaultWidth = 1000 --[[ @ 0]]
CoD.AARGametypeHeader.__defaultHeight = 150 --[[ @ 0]]
CoD.AARGametypeHeader.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.AARGametypeHeader ) --[[ @ 0]]
	self.id = "AARGametypeHeader" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	
	local GametypeImage = LUI.UIImage.new( 0, 0, 0, 120, 0, 0, 0, 120 ) --[[ @ 0]]
	GametypeImage:setAlpha( 0.5 ) --[[ @ 0]]
	self:addElement( GametypeImage ) --[[ @ 0]]
	self.GametypeImage = GametypeImage --[[ @ 0]]
	
	local GametypeGlow = LUI.UIText.new( 0, 0, 136, 991, 0, 0, 25, 100 ) --[[ @ 0]]
	GametypeGlow:setRGB( 0.9, 0.89, 0.78 ) --[[ @ 0]]
	GametypeGlow:setAlpha( 0 ) --[[ @ 0]]
	GametypeGlow:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_AB769C72F266516" ) ) --[[ @ 0]]
	GametypeGlow:setTTF( "ttmussels_demibold" ) --[[ @ 0]]
	GametypeGlow:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_90D57B1E92D39D7" ) ) --[[ @ 0]]
	GametypeGlow:setShaderVector( 0, 0.6, 0, 0, 0 ) --[[ @ 0]]
	GametypeGlow:setShaderVector( 1, 0, 0, 0, 0 ) --[[ @ 0]]
	GametypeGlow:setShaderVector( 2, 1, 1, 1, 0.6 ) --[[ @ 0]]
	GametypeGlow:setLetterSpacing( 10 ) --[[ @ 0]]
	GametypeGlow:setAlignment( Enum[@"LUIAlignment"][@"hash_558C8A85F2048829"] ) --[[ @ 0]]
	GametypeGlow:setAlignment( Enum[@"LUIAlignment"][@"hash_3F41D595A2B0EDF3"] ) --[[ @ 0]]
	self:addElement( GametypeGlow ) --[[ @ 0]]
	self.GametypeGlow = GametypeGlow --[[ @ 0]]
	
	local Gametype = LUI.UIText.new( 0, 0, 132, 1000, 0, 0, 24, 99 ) --[[ @ 0]]
	Gametype:setRGB( 0.9, 0.89, 0.78 ) --[[ @ 0]]
	Gametype:setAlpha( 0.5 ) --[[ @ 0]]
	Gametype:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_AB769C72F266516" ) ) --[[ @ 0]]
	Gametype:setTTF( "ttmussels_demibold" ) --[[ @ 0]]
	Gametype:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_171E049B161CD00A" ) ) --[[ @ 0]]
	Gametype:setLetterSpacing( 10 ) --[[ @ 0]]
	Gametype:setAlignment( Enum[@"LUIAlignment"][@"hash_558C8A85F2048829"] ) --[[ @ 0]]
	Gametype:setAlignment( Enum[@"LUIAlignment"][@"hash_E821F0ECFF8D1C7"] ) --[[ @ 0]]
	self:addElement( Gametype ) --[[ @ 0]]
	self.Gametype = Gametype --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
