-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:33
CoD.WarzoneDeathCamLabelButton = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.WarzoneDeathCamLabelButton.__defaultWidth = 176 --[[ @ 0]]
CoD.WarzoneDeathCamLabelButton.__defaultHeight = 40 --[[ @ 0]]
CoD.WarzoneDeathCamLabelButton.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.WarzoneDeathCamLabelButton ) --[[ @ 0]]
	self.id = "WarzoneDeathCamLabelButton" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local DeathCamLabel = LUI.UIText.new( 0, 0, 0, 376, 0, 0, 10, 30 ) --[[ @ 0]]
	DeathCamLabel:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	DeathCamLabel:setText( LocalizeToUpperString( @"hash_3A8BAC035CE51600" ) ) --[[ @ 0]]
	DeathCamLabel:setTTF( "ttmussels_regular" ) --[[ @ 0]]
	DeathCamLabel:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_171E049B161CD00A" ) ) --[[ @ 0]]
	DeathCamLabel:setLetterSpacing( 6 ) --[[ @ 0]]
	DeathCamLabel:setAlignment( Enum[@"LUIAlignment"][@"hash_558C8A85F2048829"] ) --[[ @ 0]]
	self:addElement( DeathCamLabel ) --[[ @ 0]]
	self.DeathCamLabel = DeathCamLabel --[[ @ 0]]
	
	local DeathCamLabelPC = nil --[[ @ 0]]
	
	DeathCamLabelPC = LUI.UIText.new( 0.5, 2.64, 0, 0, 0.5, 0.5, -10, 10 ) --[[ @ 0]]
	DeathCamLabelPC:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	DeathCamLabelPC:setAlpha( 0 ) --[[ @ 0]]
	DeathCamLabelPC:setText( LocalizeToUpperString( @"hash_41DA457B0409FB2C" ) ) --[[ @ 0]]
	DeathCamLabelPC:setTTF( "ttmussels_regular" ) --[[ @ 0]]
	DeathCamLabelPC:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_171E049B161CD00A" ) ) --[[ @ 0]]
	DeathCamLabelPC:setLetterSpacing( 6 ) --[[ @ 0]]
	DeathCamLabelPC:setAlignment( Enum[@"LUIAlignment"][@"hash_558C8A85F2048829"] ) --[[ @ 0]]
	self:addElement( DeathCamLabelPC ) --[[ @ 0]]
	self.DeathCamLabelPC = DeathCamLabelPC --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "PC",
			condition = function ( menu, element, event )
				return IsMouseOrKeyboard( f1_arg1 )
			end
		}
	} ) --[[ @ 0]]
	self:appendEventHandler( "input_source_changed", function ( f3_arg0, f3_arg1 )
		f3_arg1.menu = f3_arg1.menu or f1_arg0 --[[ @ 0]]
		f1_arg0:updateElementState( self, f3_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	local f1_local3 = self --[[ @ 0]]
	local f1_local4 = self.subscribeToModel --[[ @ 0]]
	local f1_local5 = Engine[@"GetModelForController"]( f1_arg1 ) --[[ @ 0]]
	f1_local4( f1_local3, f1_local5.LastInput, function ( f4_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f4_arg0:get(),
			modelName = "LastInput"
		} ) --[[ @ 0]]
	end, false ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.WarzoneDeathCamLabelButton.__resetProperties = function ( f5_arg0 )
	f5_arg0.DeathCamLabelPC:completeAnimation() --[[ @ 0]]
	f5_arg0.DeathCamLabel:completeAnimation() --[[ @ 0]]
	f5_arg0.DeathCamLabelPC:setAlpha( 0 ) --[[ @ 0]]
	f5_arg0.DeathCamLabel:setAlpha( 1 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.WarzoneDeathCamLabelButton.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties() --[[ @ 0]]
			f6_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	PC = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f7_arg0.DeathCamLabel:completeAnimation() --[[ @ 0]]
			f7_arg0.DeathCamLabel:setAlpha( 0 ) --[[ @ 0]]
			f7_arg0.clipFinished( f7_arg0.DeathCamLabel ) --[[ @ 0]]
			f7_arg0.DeathCamLabelPC:completeAnimation() --[[ @ 0]]
			f7_arg0.DeathCamLabelPC:setAlpha( 1 ) --[[ @ 0]]
			f7_arg0.clipFinished( f7_arg0.DeathCamLabelPC ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
