-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:48
CoD.BM_ActiveBountyInternal = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.BM_ActiveBountyInternal.__defaultWidth = 460 --[[ @ 0]]
CoD.BM_ActiveBountyInternal.__defaultHeight = 60 --[[ @ 0]]
CoD.BM_ActiveBountyInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.BM_ActiveBountyInternal ) --[[ @ 0]]
	self.id = "BM_ActiveBountyInternal" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	
	local Backing = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	Backing:setRGB( ColorSet.WarzoneTeammate3.r, ColorSet.WarzoneTeammate3.g, ColorSet.WarzoneTeammate3.b ) --[[ @ 0]]
	self:addElement( Backing ) --[[ @ 0]]
	self.Backing = Backing --[[ @ 0]]
	
	local MiddleText = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, -12, 12 ) --[[ @ 0]]
	MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b ) --[[ @ 0]]
	MiddleText:setText( LocalizeToUpperString( @"hash_0" ) ) --[[ @ 0]]
	MiddleText:setTTF( "ttmussels_regular" ) --[[ @ 0]]
	MiddleText:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_171E049B161CD00A" ) ) --[[ @ 0]]
	MiddleText:setLetterSpacing( 3 ) --[[ @ 0]]
	MiddleText:setAlignment( Enum[@"luialignment"][@"lui_alignment_center"] ) --[[ @ 0]]
	MiddleText:setAlignment( Enum[@"luialignment"][@"lui_alignment_middle"] ) --[[ @ 0]]
	self:addElement( MiddleText ) --[[ @ 0]]
	self.MiddleText = MiddleText --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
