-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:49
CoD.EmblemLayerPositionWidget = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.EmblemLayerPositionWidget.__defaultWidth = 173 --[[ @ 0]]
CoD.EmblemLayerPositionWidget.__defaultHeight = 90 --[[ @ 0]]
CoD.EmblemLayerPositionWidget.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.EmblemLayerPositionWidget ) --[[ @ 0]]
	self.id = "EmblemLayerPositionWidget" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local TopBottomText = LUI.UIText.new( 0, 0, 0, 173, 0, 0, -2, 22 ) --[[ @ 0]]
	TopBottomText:setTTF( "dinnext_regular" ) --[[ @ 0]]
	TopBottomText:setAlignment( Enum[@"luialignment"][@"lui_alignment_center"] ) --[[ @ 0]]
	TopBottomText:setAlignment( Enum[@"luialignment"][@"lui_alignment_top"] ) --[[ @ 0]]
	self:addElement( TopBottomText ) --[[ @ 0]]
	self.TopBottomText = TopBottomText --[[ @ 0]]
	
	self.TopBottomText:linkToElementModel( self, "topBottomText", true, function ( model )
		local f2_local0 = model:get() --[[ @ 0]]
		if f2_local0 ~= nil then
			TopBottomText:setText( f2_local0 ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:mergeStateConditions( {
		{
			stateName = "LowerText",
			condition = function ( menu, element, event )
				return not IsMouseOrKeyboard( f1_arg1 )
			end
		},
		{
			stateName = "KBM",
			condition = function ( menu, element, event )
				return IsMouseOrKeyboard( f1_arg1 )
			end
		}
	} ) --[[ @ 0]]
	self:appendEventHandler( "input_source_changed", function ( f5_arg0, f5_arg1 )
		f5_arg1.menu = f5_arg1.menu or f1_arg0 --[[ @ 0]]
		f1_arg0:updateElementState( self, f5_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	local f1_local2 = self --[[ @ 0]]
	local f1_local3 = self.subscribeToModel --[[ @ 0]]
	local f1_local4 = Engine[@"getmodelforcontroller"]( f1_arg1 ) --[[ @ 0]]
	f1_local3( f1_local2, f1_local4.LastInput, function ( f6_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f6_arg0:get(),
			modelName = "LastInput"
		} ) --[[ @ 0]]
	end, false ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.EmblemLayerPositionWidget.__resetProperties = function ( f7_arg0 )
	f7_arg0.TopBottomText:completeAnimation() --[[ @ 0]]
	f7_arg0.TopBottomText:setTopBottom( 0, 0, -2, 22 ) --[[ @ 0]]
	f7_arg0.TopBottomText:setRGB( 1, 1, 1 ) --[[ @ 0]]
	f7_arg0.TopBottomText:setAlpha( 1 ) --[[ @ 0]]
	f7_arg0.TopBottomText:setLetterSpacing( 0 ) --[[ @ 0]]
	f7_arg0.TopBottomText:setAlignment( Enum[@"luialignment"][@"lui_alignment_center"] ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.EmblemLayerPositionWidget.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties() --[[ @ 0]]
			f8_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	LowerText = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties() --[[ @ 0]]
			f9_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f9_arg0.TopBottomText:completeAnimation() --[[ @ 0]]
			f9_arg0.TopBottomText:setTopBottom( 0, 0, 56, 80 ) --[[ @ 0]]
			f9_arg0.clipFinished( f9_arg0.TopBottomText ) --[[ @ 0]]
		end
	},
	KBM = {
		DefaultClip = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties() --[[ @ 0]]
			f10_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f10_arg0.TopBottomText:completeAnimation() --[[ @ 0]]
			f10_arg0.TopBottomText:setTopBottom( 0, 0, 2, 15 ) --[[ @ 0]]
			f10_arg0.TopBottomText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b ) --[[ @ 0]]
			f10_arg0.TopBottomText:setAlpha( 1 ) --[[ @ 0]]
			f10_arg0.TopBottomText:setLetterSpacing( 2 ) --[[ @ 0]]
			f10_arg0.TopBottomText:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
			f10_arg0.clipFinished( f10_arg0.TopBottomText ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.EmblemLayerPositionWidget.__onClose = function ( f11_arg0 )
	f11_arg0.TopBottomText:close() --[[ @ 0]]
end
 --[[ @ 0]]
