-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:33
CoD.WarzoneStreamHider = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.WarzoneStreamHider.__defaultWidth = 1920 --[[ @ 0]]
CoD.WarzoneStreamHider.__defaultHeight = 1080 --[[ @ 0]]
CoD.WarzoneStreamHider.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.WarzoneStreamHider ) --[[ @ 0]]
	self.id = "WarzoneStreamHider" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local ObscuringBackground = LUI.UIImage.new( -0.1, 1.1, 0, 0, -0.1, 1.1, 0, 0 ) --[[ @ 0]]
	ObscuringBackground:setRGB( 0, 0, 0 ) --[[ @ 0]]
	ObscuringBackground:setAlpha( 0 ) --[[ @ 0]]
	self:addElement( ObscuringBackground ) --[[ @ 0]]
	self.ObscuringBackground = ObscuringBackground --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "Obscuring",
			condition = function ( menu, element, event )
				return IsSelfInState( self, "Obscuring" )
			end
		}
	} ) --[[ @ 0]]
	self:subscribeToGlobalModel( f1_arg1, "PerController", "deadSpectator.playerIndex", function ( model )
		local f3_local0 = self --[[ @ 0]]
		if IsControllerPlayerDead( f1_arg1 ) then
			CoD.HUDUtility.StartStreamHiding( self, f1_arg1, 3, 50, 2000, 0.9, 0.8 ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.WarzoneStreamHider.__resetProperties = function ( f4_arg0 )
	f4_arg0.ObscuringBackground:completeAnimation() --[[ @ 0]]
	f4_arg0.ObscuringBackground:setAlpha( 0 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.WarzoneStreamHider.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties() --[[ @ 0]]
			f5_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	Obscuring = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties() --[[ @ 0]]
			f6_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f6_arg0.ObscuringBackground:completeAnimation() --[[ @ 0]]
			f6_arg0.ObscuringBackground:setAlpha( 1 ) --[[ @ 0]]
			f6_arg0.clipFinished( f6_arg0.ObscuringBackground ) --[[ @ 0]]
		end,
		DefaultState = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			local f7_local0 = function ( f8_arg0 )
				f7_arg0.ObscuringBackground:beginAnimation( 100 ) --[[ @ 0]]
				f7_arg0.ObscuringBackground:setAlpha( 0 ) --[[ @ 0]]
				f7_arg0.ObscuringBackground:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted ) --[[ @ 0]]
				f7_arg0.ObscuringBackground:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f7_arg0.ObscuringBackground:completeAnimation() --[[ @ 0]]
			f7_arg0.ObscuringBackground:setAlpha( 1 ) --[[ @ 0]]
			f7_local0( f7_arg0.ObscuringBackground ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
