-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:49
require( "ui/uieditor/widgets/pc/utility/verticallistspacer" ) --[[ @ 0]]

CoD.ArenaProgressWidgetRank = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.ArenaProgressWidgetRank.__defaultWidth = 659 --[[ @ 0]]
CoD.ArenaProgressWidgetRank.__defaultHeight = 72 --[[ @ 0]]
CoD.ArenaProgressWidgetRank.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIHorizontalList.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9, 4, false ) --[[ @ 0]]
	self:setAlignment( LUI.Alignment.Left ) --[[ @ 0]]
	self:setClass( CoD.ArenaProgressWidgetRank ) --[[ @ 0]]
	self.id = "ArenaProgressWidgetRank" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	
	local PlacementText = LUI.UIText.new( 0, 0, 0, 400, 0, 0, 0, 25 ) --[[ @ 0]]
	PlacementText:setRGB( 0.67, 0.67, 0.67 ) --[[ @ 0]]
	PlacementText:setTTF( "ttmussels_demibold" ) --[[ @ 0]]
	PlacementText:setLetterSpacing( 2 ) --[[ @ 0]]
	PlacementText:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
	PlacementText:setAlignment( Enum[@"luialignment"][@"lui_alignment_top"] ) --[[ @ 0]]
	PlacementText:subscribeToGlobalModel( f1_arg1, "LeaguePlay", "leaguePlayBannerName", function ( model )
		local f2_local0 = model:get() --[[ @ 0]]
		if f2_local0 ~= nil then
			PlacementText:setText( LocalizeToUpperString( f2_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( PlacementText ) --[[ @ 0]]
	self.PlacementText = PlacementText --[[ @ 0]]
	
	local VerticalListSpacer = CoD.VerticalListSpacer.new( f1_arg0, f1_arg1, 0, 0, 396, 420, 0, 0, 0, 50 ) --[[ @ 0]]
	self:addElement( VerticalListSpacer ) --[[ @ 0]]
	self.VerticalListSpacer = VerticalListSpacer --[[ @ 0]]
	
	local TeamText = LUI.UIText.new( 0, 0, 424, 624, 0, 0, 0, 25 ) --[[ @ 0]]
	TeamText:setRGB( 0.92, 0.92, 0.92 ) --[[ @ 0]]
	TeamText:setText( LocalizeToUpperString( @"arena/rank" ) ) --[[ @ 0]]
	TeamText:setTTF( "ttmussels_demibold" ) --[[ @ 0]]
	TeamText:setLetterSpacing( 2 ) --[[ @ 0]]
	TeamText:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
	TeamText:setAlignment( Enum[@"luialignment"][@"lui_alignment_top"] ) --[[ @ 0]]
	self:addElement( TeamText ) --[[ @ 0]]
	self.TeamText = TeamText --[[ @ 0]]
	
	local VerticalListSpacer2 = CoD.VerticalListSpacer.new( f1_arg0, f1_arg1, 0, 0, 628, 634, 0, 0, 0, 50 ) --[[ @ 0]]
	self:addElement( VerticalListSpacer2 ) --[[ @ 0]]
	self.VerticalListSpacer2 = VerticalListSpacer2 --[[ @ 0]]
	
	local DisplayRank = LUI.UIText.new( 0, 0, 638, 838, 0, 0, 0, 25 ) --[[ @ 0]]
	DisplayRank:setRGB( 0.92, 0.92, 0.92 ) --[[ @ 0]]
	DisplayRank:setTTF( "ttmussels_demibold" ) --[[ @ 0]]
	DisplayRank:setLetterSpacing( 2 ) --[[ @ 0]]
	DisplayRank:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
	DisplayRank:setAlignment( Enum[@"luialignment"][@"lui_alignment_top"] ) --[[ @ 0]]
	DisplayRank:subscribeToGlobalModel( f1_arg1, "LeaguePlay", "leaguePlayRank", function ( model )
		local f3_local0 = model:get() --[[ @ 0]]
		if f3_local0 ~= nil then
			DisplayRank:setText( f3_local0 ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( DisplayRank ) --[[ @ 0]]
	self.DisplayRank = DisplayRank --[[ @ 0]]
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.ArenaProgressWidgetRank.__onClose = function ( f4_arg0 )
	f4_arg0.PlacementText:close() --[[ @ 0]]
	f4_arg0.VerticalListSpacer:close() --[[ @ 0]]
	f4_arg0.VerticalListSpacer2:close() --[[ @ 0]]
	f4_arg0.DisplayRank:close() --[[ @ 0]]
end
 --[[ @ 0]]
