-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:34
require( "ui/uieditor/widgets/cac/cac_lock" ) --[[ @ 0]]
require( "ui/uieditor/widgets/callingcards/callingcards_framewidget" ) --[[ @ 0]]
require( "ui/uieditor/widgets/store/storecommontextbacking" ) --[[ @ 0]]

CoD.Challenges_TotalMasterProgress = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.Challenges_TotalMasterProgress.__defaultWidth = 1175 --[[ @ 0]]
CoD.Challenges_TotalMasterProgress.__defaultHeight = 100 --[[ @ 0]]
CoD.Challenges_TotalMasterProgress.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.Challenges_TotalMasterProgress ) --[[ @ 0]]
	self.id = "Challenges_TotalMasterProgress" --[[ @ 0]]
	self.soundSet = "ChooseDecal" --[[ @ 0]]
	self.onlyChildrenFocusable = true --[[ @ 0]]
	self.anyChildUsesUpdateState = true --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 ) --[[ @ 0]]
	FrameBorder:setAlpha( 0.01 ) --[[ @ 0]]
	FrameBorder:setImage( RegisterImage( @"uie_ui_menu_store_common_frame" ) ) --[[ @ 0]]
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( @"uie_nineslice_add" ) ) --[[ @ 0]]
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 ) --[[ @ 0]]
	FrameBorder:setupNineSliceShader( 12, 12 ) --[[ @ 0]]
	self:addElement( FrameBorder ) --[[ @ 0]]
	self.FrameBorder = FrameBorder --[[ @ 0]]
	
	local LightOverlay = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	LightOverlay:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	LightOverlay:setAlpha( 0.01 ) --[[ @ 0]]
	self:addElement( LightOverlay ) --[[ @ 0]]
	self.LightOverlay = LightOverlay --[[ @ 0]]
	
	local MasterCallingCardIcon = CoD.CallingCards_FrameWidget.new( f1_arg0, f1_arg1, 1, 1, -456, 84, 0.5, 0.5, -45.5, 45.5 ) --[[ @ 0]]
	MasterCallingCardIcon.CardIconFrame:setScale( 0.68, 1 ) --[[ @ 0]]
	MasterCallingCardIcon:subscribeToGlobalModel( f1_arg1, "MasterCallingCard", nil, function ( model )
		MasterCallingCardIcon:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( MasterCallingCardIcon ) --[[ @ 0]]
	self.MasterCallingCardIcon = MasterCallingCardIcon --[[ @ 0]]
	
	local CallingCardLockOverlay = LUI.UIImage.new( 0, 0, 805.5, 1172.5, 0, 0, 5, 95 ) --[[ @ 0]]
	CallingCardLockOverlay:setRGB( 0, 0, 0 ) --[[ @ 0]]
	CallingCardLockOverlay:setAlpha( 0 ) --[[ @ 0]]
	self:addElement( CallingCardLockOverlay ) --[[ @ 0]]
	self.CallingCardLockOverlay = CallingCardLockOverlay --[[ @ 0]]
	
	local DotTiledBacking = CoD.StoreCommonTextBacking.new( f1_arg0, f1_arg1, 0, 0.68, 6, 4, 0.05, 0.95, 1, -1 ) --[[ @ 0]]
	DotTiledBacking:setAlpha( 0.15 ) --[[ @ 0]]
	self:addElement( DotTiledBacking ) --[[ @ 0]]
	self.DotTiledBacking = DotTiledBacking --[[ @ 0]]
	
	local ProgressBorder = LUI.UIImage.new( 0, 0.68, 4, 6, 0.05, 0.95, -1, 1 ) --[[ @ 0]]
	ProgressBorder:setAlpha( 0.1 ) --[[ @ 0]]
	ProgressBorder:setImage( RegisterImage( @"uie_ui_menu_store_common_frame" ) ) --[[ @ 0]]
	ProgressBorder:setMaterial( LUI.UIImage.GetCachedMaterial( @"uie_nineslice_add" ) ) --[[ @ 0]]
	ProgressBorder:setShaderVector( 0, 0, 0, 0, 0 ) --[[ @ 0]]
	ProgressBorder:setupNineSliceShader( 12, 12 ) --[[ @ 0]]
	self:addElement( ProgressBorder ) --[[ @ 0]]
	self.ProgressBorder = ProgressBorder --[[ @ 0]]
	
	local ProgressBar = LUI.UIImage.new( 0, 0.68, 6, 4, 0.06, 0.94, 0, 0 ) --[[ @ 0]]
	ProgressBar:setRGB( 1, 0.36, 0 ) --[[ @ 0]]
	ProgressBar:setAlpha( 0.15 ) --[[ @ 0]]
	ProgressBar:setMaterial( LUI.UIImage.GetCachedMaterial( @"uie_wipe" ) ) --[[ @ 0]]
	ProgressBar:setShaderVector( 1, 0, 0, 0, 0 ) --[[ @ 0]]
	ProgressBar:setShaderVector( 2, 1, 0, 0, 0 ) --[[ @ 0]]
	ProgressBar:setShaderVector( 3, 0, 0, 0, 0 ) --[[ @ 0]]
	ProgressBar:setShaderVector( 4, 0, 0, 0, 0 ) --[[ @ 0]]
	ProgressBar:linkToElementModel( self, "percentComplete", true, function ( model )
		local f3_local0 = model:get() --[[ @ 0]]
		if f3_local0 ~= nil then
			ProgressBar:setShaderVector( 0, CoD.GetVectorComponentFromString( f3_local0, 1 ), CoD.GetVectorComponentFromString( f3_local0, 2 ), CoD.GetVectorComponentFromString( f3_local0, 3 ), CoD.GetVectorComponentFromString( f3_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( ProgressBar ) --[[ @ 0]]
	self.ProgressBar = ProgressBar --[[ @ 0]]
	
	local LockIconBacking = LUI.UIImage.new( 0.73, 0.73, 105.5, 145.5, 0, 0, 30, 70 ) --[[ @ 0]]
	LockIconBacking:setRGB( 0, 0, 0 ) --[[ @ 0]]
	LockIconBacking:setAlpha( 0.85 ) --[[ @ 0]]
	LockIconBacking:setMaterial( LUI.UIImage.GetCachedMaterial( @"uie_feather_edges" ) ) --[[ @ 0]]
	LockIconBacking:setShaderVector( 0, 0.02, 0.02, 0.02, 0.02 ) --[[ @ 0]]
	self:addElement( LockIconBacking ) --[[ @ 0]]
	self.LockIconBacking = LockIconBacking --[[ @ 0]]
	
	local LockIconBackingTexture = LUI.UIImage.new( 0.74, 0.74, 101.5, 141.5, 0, 0, 30, 70 ) --[[ @ 0]]
	LockIconBackingTexture:setAlpha( 0.15 ) --[[ @ 0]]
	LockIconBackingTexture:setImage( RegisterImage( @"uie_ui_hud_notifications_pixelpattern" ) ) --[[ @ 0]]
	LockIconBackingTexture:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_16CBE95C250C6D15" ) ) --[[ @ 0]]
	LockIconBackingTexture:setShaderVector( 0, 0, 0, 0, 0 ) --[[ @ 0]]
	LockIconBackingTexture:setupNineSliceShader( 128, 128 ) --[[ @ 0]]
	self:addElement( LockIconBackingTexture ) --[[ @ 0]]
	self.LockIconBackingTexture = LockIconBackingTexture --[[ @ 0]]
	
	local LockedIcon = CoD.cac_lock.new( f1_arg0, f1_arg1, 1, 1, -204, -168, 0.5, 0.5, -18, 18 ) --[[ @ 0]]
	self:addElement( LockedIcon ) --[[ @ 0]]
	self.LockedIcon = LockedIcon --[[ @ 0]]
	
	local CallingCardDescription = LUI.UIText.new( 0, 0, 24, 780, 0, 0, 62.5, 80.5 ) --[[ @ 0]]
	CallingCardDescription:setRGB( ColorSet.T8__OFF__GRAY.r, ColorSet.T8__OFF__GRAY.g, ColorSet.T8__OFF__GRAY.b ) --[[ @ 0]]
	CallingCardDescription:setTTF( "dinnext_regular" ) --[[ @ 0]]
	CallingCardDescription:setLetterSpacing( 0.5 ) --[[ @ 0]]
	CallingCardDescription:setAlignment( Enum[@"LUIAlignment"][@"hash_558C8A85F2048829"] ) --[[ @ 0]]
	CallingCardDescription:setAlignment( Enum[@"LUIAlignment"][@"hash_3F41D595A2B0EDF3"] ) --[[ @ 0]]
	CallingCardDescription:linkToElementModel( self, "description", true, function ( model )
		local f4_local0 = model:get() --[[ @ 0]]
		if f4_local0 ~= nil then
			CallingCardDescription:setText( CoD.BaseUtility.AlreadyLocalized( f4_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( CallingCardDescription ) --[[ @ 0]]
	self.CallingCardDescription = CallingCardDescription --[[ @ 0]]
	
	local CallingCardName = LUI.UIText.new( 0, 0, 24, 479, 0, 0, 21.5, 57.5 ) --[[ @ 0]]
	CallingCardName:setTTF( "ttmussels_regular" ) --[[ @ 0]]
	CallingCardName:setLetterSpacing( 4 ) --[[ @ 0]]
	CallingCardName:setAlignment( Enum[@"LUIAlignment"][@"hash_558C8A85F2048829"] ) --[[ @ 0]]
	CallingCardName:setAlignment( Enum[@"LUIAlignment"][@"hash_3F41D595A2B0EDF3"] ) --[[ @ 0]]
	CallingCardName:linkToElementModel( self, "title", true, function ( model )
		local f5_local0 = model:get() --[[ @ 0]]
		if f5_local0 ~= nil then
			CallingCardName:setText( ConvertToUpperString( f5_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( CallingCardName ) --[[ @ 0]]
	self.CallingCardName = CallingCardName --[[ @ 0]]
	
	local CornerPip = LUI.UIImage.new( 0, 0, 0, 15, 1, 1, -15, 0 ) --[[ @ 0]]
	CornerPip:setAlpha( 0.15 ) --[[ @ 0]]
	CornerPip:setZRot( -90 ) --[[ @ 0]]
	CornerPip:setImage( RegisterImage( @"uie_ui_menu_specialist_hub_window_corner" ) ) --[[ @ 0]]
	self:addElement( CornerPip ) --[[ @ 0]]
	self.CornerPip = CornerPip --[[ @ 0]]
	
	local CornerPip4 = LUI.UIImage.new( 1, 1, -15, 0, 1, 1, -15, 0 ) --[[ @ 0]]
	CornerPip4:setAlpha( 0.15 ) --[[ @ 0]]
	CornerPip4:setImage( RegisterImage( @"uie_ui_menu_specialist_hub_window_corner" ) ) --[[ @ 0]]
	self:addElement( CornerPip4 ) --[[ @ 0]]
	self.CornerPip4 = CornerPip4 --[[ @ 0]]
	
	local CornerPip3 = LUI.UIImage.new( 0, 0, 0, 15, 0, 0, 0, 15 ) --[[ @ 0]]
	CornerPip3:setAlpha( 0.15 ) --[[ @ 0]]
	CornerPip3:setZRot( 180 ) --[[ @ 0]]
	CornerPip3:setImage( RegisterImage( @"uie_ui_menu_specialist_hub_window_corner" ) ) --[[ @ 0]]
	self:addElement( CornerPip3 ) --[[ @ 0]]
	self.CornerPip3 = CornerPip3 --[[ @ 0]]
	
	local CornerPip2 = LUI.UIImage.new( 1, 1, -15, 0, 0, 0, 0, 15 ) --[[ @ 0]]
	CornerPip2:setAlpha( 0.15 ) --[[ @ 0]]
	CornerPip2:setZRot( 90 ) --[[ @ 0]]
	CornerPip2:setImage( RegisterImage( @"uie_ui_menu_specialist_hub_window_corner" ) ) --[[ @ 0]]
	self:addElement( CornerPip2 ) --[[ @ 0]]
	self.CornerPip2 = CornerPip2 --[[ @ 0]]
	
	local percentText = LUI.UIText.new( 0.5, 0.5, 102, 192, 0.5, 0.5, -13.5, 13.5 ) --[[ @ 0]]
	percentText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	percentText:setAlpha( 0.8 ) --[[ @ 0]]
	percentText:setTTF( "dinnext_regular" ) --[[ @ 0]]
	percentText:setAlignment( Enum[@"LUIAlignment"][@"hash_3830CFD395E6AA0A"] ) --[[ @ 0]]
	percentText:setAlignment( Enum[@"LUIAlignment"][@"hash_3F41D595A2B0EDF3"] ) --[[ @ 0]]
	percentText:linkToElementModel( self, "percentComplete", true, function ( model )
		local f6_local0 = model:get() --[[ @ 0]]
		if f6_local0 ~= nil then
			percentText:setText( NumberAsPercentRounded( f6_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( percentText ) --[[ @ 0]]
	self.percentText = percentText --[[ @ 0]]
	
	local CompletedImage = LUI.UIImage.new( 0, 0, 642, 702, 0.5, 0.5, -30, 30 ) --[[ @ 0]]
	CompletedImage:setAlpha( 0 ) --[[ @ 0]]
	CompletedImage:setImage( RegisterImage( @"uie_ui_icon_challenges_complete_small" ) ) --[[ @ 0]]
	self:addElement( CompletedImage ) --[[ @ 0]]
	self.CompletedImage = CompletedImage --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "Locked",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsSelfModelValueTrue( element, f1_arg1, "isLocked" )
			end
		},
		{
			stateName = "Completed",
			condition = function ( menu, element, event )
				return AlwaysTrue()
			end
		}
	} ) --[[ @ 0]]
	self:linkToElementModel( self, "isLocked", true, function ( model )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "isLocked"
		} ) --[[ @ 0]]
	end ) --[[ @ 0]]
	MasterCallingCardIcon.id = "MasterCallingCardIcon" --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.Challenges_TotalMasterProgress.__resetProperties = function ( f10_arg0 )
	f10_arg0.LockedIcon:completeAnimation() --[[ @ 0]]
	f10_arg0.LockIconBacking:completeAnimation() --[[ @ 0]]
	f10_arg0.LockIconBackingTexture:completeAnimation() --[[ @ 0]]
	f10_arg0.CallingCardLockOverlay:completeAnimation() --[[ @ 0]]
	f10_arg0.ProgressBar:completeAnimation() --[[ @ 0]]
	f10_arg0.CallingCardName:completeAnimation() --[[ @ 0]]
	f10_arg0.percentText:completeAnimation() --[[ @ 0]]
	f10_arg0.CompletedImage:completeAnimation() --[[ @ 0]]
	f10_arg0.LockedIcon:setAlpha( 1 ) --[[ @ 0]]
	f10_arg0.LockIconBacking:setAlpha( 0.85 ) --[[ @ 0]]
	f10_arg0.LockIconBackingTexture:setAlpha( 0.15 ) --[[ @ 0]]
	f10_arg0.CallingCardLockOverlay:setAlpha( 0 ) --[[ @ 0]]
	f10_arg0.ProgressBar:setAlpha( 0.15 ) --[[ @ 0]]
	f10_arg0.CallingCardName:setRGB( 1, 1, 1 ) --[[ @ 0]]
	f10_arg0.percentText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	f10_arg0.CompletedImage:setAlpha( 0 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.Challenges_TotalMasterProgress.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties() --[[ @ 0]]
			f11_arg0:setupElementClipCounter( 3 ) --[[ @ 0]]
			f11_arg0.LockIconBacking:completeAnimation() --[[ @ 0]]
			f11_arg0.LockIconBacking:setAlpha( 0 ) --[[ @ 0]]
			f11_arg0.clipFinished( f11_arg0.LockIconBacking ) --[[ @ 0]]
			f11_arg0.LockIconBackingTexture:completeAnimation() --[[ @ 0]]
			f11_arg0.LockIconBackingTexture:setAlpha( 0 ) --[[ @ 0]]
			f11_arg0.clipFinished( f11_arg0.LockIconBackingTexture ) --[[ @ 0]]
			f11_arg0.LockedIcon:completeAnimation() --[[ @ 0]]
			f11_arg0.LockedIcon:setAlpha( 0 ) --[[ @ 0]]
			f11_arg0.clipFinished( f11_arg0.LockedIcon ) --[[ @ 0]]
		end
	},
	Locked = {
		DefaultClip = function ( f12_arg0, f12_arg1 )
			f12_arg0:__resetProperties() --[[ @ 0]]
			f12_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f12_arg0.CallingCardLockOverlay:completeAnimation() --[[ @ 0]]
			f12_arg0.CallingCardLockOverlay:setAlpha( 0.85 ) --[[ @ 0]]
			f12_arg0.clipFinished( f12_arg0.CallingCardLockOverlay ) --[[ @ 0]]
		end
	},
	Completed = {
		DefaultClip = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties() --[[ @ 0]]
			f13_arg0:setupElementClipCounter( 7 ) --[[ @ 0]]
			f13_arg0.ProgressBar:completeAnimation() --[[ @ 0]]
			f13_arg0.ProgressBar:setAlpha( 0 ) --[[ @ 0]]
			f13_arg0.clipFinished( f13_arg0.ProgressBar ) --[[ @ 0]]
			f13_arg0.LockIconBacking:completeAnimation() --[[ @ 0]]
			f13_arg0.LockIconBacking:setAlpha( 0 ) --[[ @ 0]]
			f13_arg0.clipFinished( f13_arg0.LockIconBacking ) --[[ @ 0]]
			f13_arg0.LockIconBackingTexture:completeAnimation() --[[ @ 0]]
			f13_arg0.LockIconBackingTexture:setAlpha( 0 ) --[[ @ 0]]
			f13_arg0.clipFinished( f13_arg0.LockIconBackingTexture ) --[[ @ 0]]
			f13_arg0.LockedIcon:completeAnimation() --[[ @ 0]]
			f13_arg0.LockedIcon:setAlpha( 0 ) --[[ @ 0]]
			f13_arg0.clipFinished( f13_arg0.LockedIcon ) --[[ @ 0]]
			f13_arg0.CallingCardName:completeAnimation() --[[ @ 0]]
			f13_arg0.CallingCardName:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b ) --[[ @ 0]]
			f13_arg0.clipFinished( f13_arg0.CallingCardName ) --[[ @ 0]]
			f13_arg0.percentText:completeAnimation() --[[ @ 0]]
			f13_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b ) --[[ @ 0]]
			f13_arg0.clipFinished( f13_arg0.percentText ) --[[ @ 0]]
			f13_arg0.CompletedImage:completeAnimation() --[[ @ 0]]
			f13_arg0.CompletedImage:setAlpha( 1 ) --[[ @ 0]]
			f13_arg0.clipFinished( f13_arg0.CompletedImage ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.Challenges_TotalMasterProgress.__onClose = function ( f14_arg0 )
	f14_arg0.MasterCallingCardIcon:close() --[[ @ 0]]
	f14_arg0.DotTiledBacking:close() --[[ @ 0]]
	f14_arg0.ProgressBar:close() --[[ @ 0]]
	f14_arg0.LockedIcon:close() --[[ @ 0]]
	f14_arg0.CallingCardDescription:close() --[[ @ 0]]
	f14_arg0.CallingCardName:close() --[[ @ 0]]
	f14_arg0.percentText:close() --[[ @ 0]]
end
 --[[ @ 0]]
