-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:50
require( "x64:3e272191e46af824" ) --[[ @ 0]]
require( "x64:dc74d5014cfb5b9" ) --[[ @ 0]]
require( "x64:62fffefea131705b" ) --[[ @ 0]]
require( "x64:d0fe15b75d77a7" ) --[[ @ 0]]

CoD.BMTallItemContainer = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.BMTallItemContainer.__defaultWidth = 240 --[[ @ 0]]
CoD.BMTallItemContainer.__defaultHeight = 510 --[[ @ 0]]
CoD.BMTallItemContainer.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.BMTallItemContainer ) --[[ @ 0]]
	self.id = "BMTallItemContainer" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	self.onlyChildrenFocusable = true --[[ @ 0]]
	self.anyChildUsesUpdateState = true --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local CardStack = CoD.BlackJacksShopCardStackSunset.new( f1_arg0, f1_arg1, 0.5, 0.5, 88, 152, 0.5, 0.5, -256, 256 ) --[[ @ 0]]
	CardStack:linkToElementModel( self, nil, false, function ( model )
		CardStack:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( CardStack ) --[[ @ 0]]
	self.CardStack = CardStack --[[ @ 0]]
	
	local BMTallItem = CoD.BMTallItem.new( f1_arg0, f1_arg1, 0.5, 0.5, -120, 120, 0.5, 0.5, -255, 255 ) --[[ @ 0]]
	BMTallItem:linkToElementModel( self, nil, false, function ( model )
		BMTallItem:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( BMTallItem ) --[[ @ 0]]
	self.BMTallItem = BMTallItem --[[ @ 0]]
	
	local ItemHintText = CoD.CommonToolTip.new( f1_arg0, f1_arg1, 0.5, 0.5, -135, 135, 1, 1, 52, 97 ) --[[ @ 0]]
	ItemHintText:mergeStateConditions( {
		{
			stateName = "Mouse",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		},
		{
			stateName = "NoHintText",
			condition = function ( menu, element, event )
				return not IsBooleanDvarSet( "loot_sunsetBlackjackShopActive" )
			end
		},
		{
			stateName = "CenterAlign",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		}
	} ) --[[ @ 0]]
	ItemHintText:setAlpha( 0 ) --[[ @ 0]]
	ItemHintText:linkToElementModel( self, "toolTipText", true, function ( model )
		local f7_local0 = model:get() --[[ @ 0]]
		if f7_local0 ~= nil then
			ItemHintText.textCenterAlign:setText( Engine[@"hash_4F9F1239CFD921FE"]( f7_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( ItemHintText ) --[[ @ 0]]
	self.ItemHintText = ItemHintText --[[ @ 0]]
	
	local BMStackPips = CoD.BMStackPips.new( f1_arg0, f1_arg1, 0, 0, 90, 150, 0, 0, 529.5, 541.5 ) --[[ @ 0]]
	BMStackPips:mergeStateConditions( {
		{
			stateName = "Visible",
			condition = function ( menu, element, event )
				local f8_local0 = IsBooleanDvarSet( "loot_sunsetBlackjackShopActive" ) --[[ @ 0]]
				if f8_local0 then
					f8_local0 = IsMenuPropertyValue( menu, "_currentTab", "itemshop" ) --[[ @ 0]]
					if f8_local0 then
						if not CoD.ModelUtility.IsSelfModelValueNilOrTrue( element, f1_arg1, "emptyItem" ) then
							f8_local0 = CoD.BaseUtility.DoesElementOrChildHaveFocus( self, "BMTallItem" ) --[[ @ 0]]
						else
							f8_local0 = false --[[ @ 0]]
						end
					end
				end
				return f8_local0
			end
		}
	} ) --[[ @ 0]]
	BMStackPips:linkToElementModel( BMStackPips, "emptyItem", true, function ( model )
		f1_arg0:updateElementState( BMStackPips, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "emptyItem"
		} ) --[[ @ 0]]
	end ) --[[ @ 0]]
	BMStackPips:appendEventHandler( "record_curr_focused_elem_id", function ( f10_arg0, f10_arg1 )
		f10_arg1.menu = f10_arg1.menu or f1_arg0 --[[ @ 0]]
		f1_arg0:updateElementState( BMStackPips, f10_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	BMStackPips:setAlpha( 0 ) --[[ @ 0]]
	BMStackPips:linkToElementModel( self, nil, false, function ( model )
		BMStackPips:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( BMStackPips ) --[[ @ 0]]
	self.BMStackPips = BMStackPips --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "PC",
			condition = function ( menu, element, event )
				return IsPC()
			end
		}
	} ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalFirst( self, "childFocusGained", function ( element )
		UpdateSelfElementState( f1_arg0, self.BMStackPips, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalFirst( self, "childFocusLost", function ( element )
		UpdateSelfElementState( f1_arg0, self.BMStackPips, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	BMTallItem.id = "BMTallItem" --[[ @ 0]]
	self.__defaultFocus = BMTallItem --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.BMTallItemContainer.__resetProperties = function ( f15_arg0 )
	f15_arg0.BMTallItem:completeAnimation() --[[ @ 0]]
	f15_arg0.ItemHintText:completeAnimation() --[[ @ 0]]
	f15_arg0.BMStackPips:completeAnimation() --[[ @ 0]]
	f15_arg0.BMTallItem:setScale( 1, 1 ) --[[ @ 0]]
	f15_arg0.ItemHintText:setAlpha( 0 ) --[[ @ 0]]
	f15_arg0.BMStackPips:setAlpha( 0 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.BMTallItemContainer.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties() --[[ @ 0]]
			f16_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end,
		ChildFocus = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties() --[[ @ 0]]
			f17_arg0:setupElementClipCounter( 3 ) --[[ @ 0]]
			f17_arg0.BMTallItem:completeAnimation() --[[ @ 0]]
			f17_arg0.BMTallItem:setScale( 1.05, 1.05 ) --[[ @ 0]]
			f17_arg0.clipFinished( f17_arg0.BMTallItem ) --[[ @ 0]]
			local f17_local0 = function ( f18_arg0 )
				local f18_local0 = function ( f19_arg0 )
					f19_arg0:beginAnimation( 199 ) --[[ @ 0]]
					f19_arg0:setAlpha( 0 ) --[[ @ 0]]
					f19_arg0:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f17_arg0.ItemHintText:beginAnimation( 10000 ) --[[ @ 0]]
				f17_arg0.ItemHintText:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted ) --[[ @ 0]]
				f17_arg0.ItemHintText:registerEventHandler( "transition_complete_keyframe", f18_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f17_arg0.ItemHintText:completeAnimation() --[[ @ 0]]
			f17_arg0.ItemHintText:setAlpha( 1 ) --[[ @ 0]]
			f17_local0( f17_arg0.ItemHintText ) --[[ @ 0]]
			f17_arg0.BMStackPips:completeAnimation() --[[ @ 0]]
			f17_arg0.BMStackPips:setAlpha( 1 ) --[[ @ 0]]
			f17_arg0.clipFinished( f17_arg0.BMStackPips ) --[[ @ 0]]
		end,
		GainChildFocus = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties() --[[ @ 0]]
			f20_arg0:setupElementClipCounter( 3 ) --[[ @ 0]]
			local f20_local0 = function ( f21_arg0 )
				f20_arg0.BMTallItem:beginAnimation( 200, Enum[@"luitween"][@"luitween_ease_both"] ) --[[ @ 0]]
				f20_arg0.BMTallItem:setScale( 1.05, 1.05 ) --[[ @ 0]]
				f20_arg0.BMTallItem:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted ) --[[ @ 0]]
				f20_arg0.BMTallItem:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f20_arg0.BMTallItem:completeAnimation() --[[ @ 0]]
			f20_arg0.BMTallItem:setScale( 1, 1 ) --[[ @ 0]]
			f20_local0( f20_arg0.BMTallItem ) --[[ @ 0]]
			local f20_local1 = function ( f22_arg0 )
				f20_arg0.ItemHintText:beginAnimation( 200 ) --[[ @ 0]]
				f20_arg0.ItemHintText:setAlpha( 1 ) --[[ @ 0]]
				f20_arg0.ItemHintText:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted ) --[[ @ 0]]
				f20_arg0.ItemHintText:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f20_arg0.ItemHintText:completeAnimation() --[[ @ 0]]
			f20_arg0.ItemHintText:setAlpha( 0 ) --[[ @ 0]]
			f20_local1( f20_arg0.ItemHintText ) --[[ @ 0]]
			f20_arg0.BMStackPips:completeAnimation() --[[ @ 0]]
			f20_arg0.BMStackPips:setAlpha( 1 ) --[[ @ 0]]
			f20_arg0.clipFinished( f20_arg0.BMStackPips ) --[[ @ 0]]
		end,
		LoseChildFocus = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties() --[[ @ 0]]
			f23_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			local f23_local0 = function ( f24_arg0 )
				f23_arg0.BMTallItem:beginAnimation( 200, Enum[@"luitween"][@"luitween_ease_both"] ) --[[ @ 0]]
				f23_arg0.BMTallItem:setScale( 1, 1 ) --[[ @ 0]]
				f23_arg0.BMTallItem:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted ) --[[ @ 0]]
				f23_arg0.BMTallItem:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f23_arg0.BMTallItem:completeAnimation() --[[ @ 0]]
			f23_arg0.BMTallItem:setScale( 1.05, 1.05 ) --[[ @ 0]]
			f23_local0( f23_arg0.BMTallItem ) --[[ @ 0]]
		end
	},
	PC = {
		DefaultClip = function ( f25_arg0, f25_arg1 )
			f25_arg0:__resetProperties() --[[ @ 0]]
			f25_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.BMTallItemContainer.__onClose = function ( f26_arg0 )
	f26_arg0.CardStack:close() --[[ @ 0]]
	f26_arg0.BMTallItem:close() --[[ @ 0]]
	f26_arg0.ItemHintText:close() --[[ @ 0]]
	f26_arg0.BMStackPips:close() --[[ @ 0]]
end
 --[[ @ 0]]
