-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:50
CoD.TimerRight = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.TimerRight.__defaultWidth = 355 --[[ @ 0]]
CoD.TimerRight.__defaultHeight = 50 --[[ @ 0]]
CoD.TimerRight.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.TimerRight ) --[[ @ 0]]
	self.id = "TimerRight" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	
	local TextBox2 = LUI.UIText.new( 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	TextBox2:setRGB( ColorSet.StoreAvailabilityTimer.r, ColorSet.StoreAvailabilityTimer.g, ColorSet.StoreAvailabilityTimer.b ) --[[ @ 0]]
	TextBox2:setText( "" ) --[[ @ 0]]
	TextBox2:setTTF( "dinnext_regular" ) --[[ @ 0]]
	TextBox2:setLetterSpacing( -1 ) --[[ @ 0]]
	TextBox2:setAlignment( Enum[@"luialignment"][@"lui_alignment_right"] ) --[[ @ 0]]
	self:addElement( TextBox2 ) --[[ @ 0]]
	self.TextBox2 = TextBox2 --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
