-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:34
require( "x64:7caf02dcc11642e8" ) --[[ @ 0]]

CoD.PurchaseTiers = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.PurchaseTiers.__defaultWidth = 180 --[[ @ 0]]
CoD.PurchaseTiers.__defaultHeight = 90 --[[ @ 0]]
CoD.PurchaseTiers.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.PurchaseTiers ) --[[ @ 0]]
	self.id = "PurchaseTiers" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	self.anyChildUsesUpdateState = true --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local Black = LUI.UIImage.new( 0, 0, 22.5, 157.5, 0, 0, -397.5, -395.5 ) --[[ @ 0]]
	Black:setRGB( 0, 0, 0 ) --[[ @ 0]]
	Black:setAlpha( 0 ) --[[ @ 0]]
	self:addElement( Black ) --[[ @ 0]]
	self.Black = Black --[[ @ 0]]
	
	local PurchaseBand3 = LUI.UIImage.new( 0, 0, 11, 169, 0, 0, -404.5, -388.5 ) --[[ @ 0]]
	PurchaseBand3:setImage( RegisterImage( @"hash_7D77FEBA1B6DF8BA" ) ) --[[ @ 0]]
	PurchaseBand3:setMaterial( LUI.UIImage.GetCachedMaterial( @"uie_nineslice_add" ) ) --[[ @ 0]]
	PurchaseBand3:setShaderVector( 0, 0, 0, 0, 0 ) --[[ @ 0]]
	PurchaseBand3:setupNineSliceShader( 20, 8 ) --[[ @ 0]]
	self:addElement( PurchaseBand3 ) --[[ @ 0]]
	self.PurchaseBand3 = PurchaseBand3 --[[ @ 0]]
	
	local Internal = CoD.PurchaseTiersInternal.new( f1_arg0, f1_arg1, 0.5, 0.5, -90, 90, 0, 0, 4, 71 ) --[[ @ 0]]
	self:addElement( Internal ) --[[ @ 0]]
	self.Internal = Internal --[[ @ 0]]
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.PurchaseTiers.__resetProperties = function ( f2_arg0 )
	f2_arg0.Black:completeAnimation() --[[ @ 0]]
	f2_arg0.PurchaseBand3:completeAnimation() --[[ @ 0]]
	f2_arg0.Black:setLeftRight( 0, 0, 22.5, 157.5 ) --[[ @ 0]]
	f2_arg0.Black:setTopBottom( 0, 0, -397.5, -395.5 ) --[[ @ 0]]
	f2_arg0.PurchaseBand3:setTopBottom( 0, 0, -404.5, -388.5 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.PurchaseTiers.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f3_arg0, f3_arg1 )
			f3_arg0:__resetProperties() --[[ @ 0]]
			f3_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	OneStream = {
		DefaultClip = function ( f4_arg0, f4_arg1 )
			f4_arg0:__resetProperties() --[[ @ 0]]
			f4_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f4_arg0.Black:completeAnimation() --[[ @ 0]]
			f4_arg0.Black:setTopBottom( 0, 0, -235.5, -233.5 ) --[[ @ 0]]
			f4_arg0.clipFinished( f4_arg0.Black ) --[[ @ 0]]
			f4_arg0.PurchaseBand3:completeAnimation() --[[ @ 0]]
			f4_arg0.PurchaseBand3:setTopBottom( 0, 0, -242.5, -226.5 ) --[[ @ 0]]
			f4_arg0.clipFinished( f4_arg0.PurchaseBand3 ) --[[ @ 0]]
		end
	},
	TwoStream = {
		DefaultClip = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties() --[[ @ 0]]
			f5_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f5_arg0.Black:completeAnimation() --[[ @ 0]]
			f5_arg0.Black:setLeftRight( 0, 0, 22.5, 157.5 ) --[[ @ 0]]
			f5_arg0.Black:setTopBottom( 0, 0, -397.5, -395.5 ) --[[ @ 0]]
			f5_arg0.clipFinished( f5_arg0.Black ) --[[ @ 0]]
			f5_arg0.PurchaseBand3:completeAnimation() --[[ @ 0]]
			f5_arg0.PurchaseBand3:setTopBottom( 0, 0, -404.5, -388.5 ) --[[ @ 0]]
			f5_arg0.clipFinished( f5_arg0.PurchaseBand3 ) --[[ @ 0]]
		end
	},
	ThreeStream = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties() --[[ @ 0]]
			f6_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f6_arg0.Black:completeAnimation() --[[ @ 0]]
			f6_arg0.Black:setTopBottom( 0, 0, -559.5, -557.5 ) --[[ @ 0]]
			f6_arg0.clipFinished( f6_arg0.Black ) --[[ @ 0]]
			f6_arg0.PurchaseBand3:completeAnimation() --[[ @ 0]]
			f6_arg0.PurchaseBand3:setTopBottom( 0, 0, -566.5, -550.5 ) --[[ @ 0]]
			f6_arg0.clipFinished( f6_arg0.PurchaseBand3 ) --[[ @ 0]]
		end
	},
	FourStream = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f7_arg0.Black:completeAnimation() --[[ @ 0]]
			f7_arg0.Black:setTopBottom( 0, 0, -721.5, -719.5 ) --[[ @ 0]]
			f7_arg0.clipFinished( f7_arg0.Black ) --[[ @ 0]]
			f7_arg0.PurchaseBand3:completeAnimation() --[[ @ 0]]
			f7_arg0.PurchaseBand3:setTopBottom( 0, 0, -728.5, -712.5 ) --[[ @ 0]]
			f7_arg0.clipFinished( f7_arg0.PurchaseBand3 ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.PurchaseTiers.__onClose = function ( f8_arg0 )
	f8_arg0.Internal:close() --[[ @ 0]]
end
 --[[ @ 0]]
