-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:34
require( "x64:55677da2fba4b1c9" ) --[[ @ 0]]

CoD.ZMTributeSplash = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.ZMTributeSplash.__defaultWidth = 1920 --[[ @ 0]]
CoD.ZMTributeSplash.__defaultHeight = 230 --[[ @ 0]]
CoD.ZMTributeSplash.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	CoD.BaseUtility.InitControllerModel( f1_arg1, "zmhud.playTributeSplash", 0 ) --[[ @ 0]]
	self:setClass( CoD.ZMTributeSplash ) --[[ @ 0]]
	self.id = "ZMTributeSplash" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local Text = LUI.UIText.new( 0, 0, 0, 1920, 0, 0, 112, 179 ) --[[ @ 0]]
	Text:setRGB( 0.96, 0.67, 0 ) --[[ @ 0]]
	Text:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_26FC3CB1BAC1018" ) ) --[[ @ 0]]
	Text:setTTF( "skorzhen" ) --[[ @ 0]]
	Text:setMaterial( LUI.UIImage.GetCachedMaterial( @"hash_90D57B1E92D39D7" ) ) --[[ @ 0]]
	Text:setShaderVector( 0, 0.02, 0, 0, 0 ) --[[ @ 0]]
	Text:setShaderVector( 1, 0.04, 0, 0, 0 ) --[[ @ 0]]
	Text:setShaderVector( 2, 0, 0, 0, 1 ) --[[ @ 0]]
	Text:setAlignment( Enum[@"LUIAlignment"][@"hash_1FEEB12BCB0D7041"] ) --[[ @ 0]]
	Text:setAlignment( Enum[@"LUIAlignment"][@"hash_3F41D595A2B0EDF3"] ) --[[ @ 0]]
	self:addElement( Text ) --[[ @ 0]]
	self.Text = Text --[[ @ 0]]
	
	local ZMTitleFog = CoD.ZM_Title_Fog.new( f1_arg0, f1_arg1, 0, 0, 691, 1203, 0, 0, -166, 346 ) --[[ @ 0]]
	ZMTitleFog:setAlpha( 0 ) --[[ @ 0]]
	ZMTitleFog:setScale( 1.5, 0.8 ) --[[ @ 0]]
	self:addElement( ZMTitleFog ) --[[ @ 0]]
	self.ZMTitleFog = ZMTitleFog --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "ItemUpgraded",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsModelValueGreaterThan( f1_arg1, "luielement.zm_red_challenges_hud.tributeAvailable", 1 )
			end
		},
		{
			stateName = "ItemAvailable",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsModelValueGreaterThan( f1_arg1, "luielement.zm_red_challenges_hud.tributeAvailable", 0 )
			end
		}
	} ) --[[ @ 0]]
	local f1_local3 = self --[[ @ 0]]
	local f1_local4 = self.subscribeToModel --[[ @ 0]]
	local f1_local5 = Engine[@"GetModelForController"]( f1_arg1 ) --[[ @ 0]]
	f1_local4( f1_local3, f1_local5["luielement.zm_red_challenges_hud.tributeAvailable"], function ( f4_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f4_arg0:get(),
			modelName = "luielement.zm_red_challenges_hud.tributeAvailable"
		} ) --[[ @ 0]]
	end, false ) --[[ @ 0]]
	self:subscribeToGlobalModel( f1_arg1, "PerController", "zmhud.playTributeSplash", function ( model )
		local f5_local0 = self --[[ @ 0]]
		if CoD.ModelUtility.IsModelValueGreaterThan( f1_arg1, "zmhud.playTributeSplash", 0 ) then
			PlayClip( self, "DefaultClip", f1_arg1 ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.ZMTributeSplash.__resetProperties = function ( f6_arg0 )
	f6_arg0.Text:completeAnimation() --[[ @ 0]]
	f6_arg0.ZMTitleFog:completeAnimation() --[[ @ 0]]
	f6_arg0.Text:setLeftRight( 0, 0, 0, 1920 ) --[[ @ 0]]
	f6_arg0.Text:setTopBottom( 0, 0, 112, 179 ) --[[ @ 0]]
	f6_arg0.Text:setAlpha( 1 ) --[[ @ 0]]
	f6_arg0.Text:setScale( 1, 1 ) --[[ @ 0]]
	f6_arg0.Text:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_26FC3CB1BAC1018" ) ) --[[ @ 0]]
	f6_arg0.ZMTitleFog:setTopBottom( 0, 0, -166, 346 ) --[[ @ 0]]
	f6_arg0.ZMTitleFog:setAlpha( 0 ) --[[ @ 0]]
	f6_arg0.ZMTitleFog:setScale( 1.5, 0.8 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.ZMTributeSplash.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f7_arg0.Text:completeAnimation() --[[ @ 0]]
			f7_arg0.Text:setAlpha( 0 ) --[[ @ 0]]
			f7_arg0.clipFinished( f7_arg0.Text ) --[[ @ 0]]
		end
	},
	ItemUpgraded = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties() --[[ @ 0]]
			f8_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			local f8_local0 = function ( f9_arg0 )
				local f9_local0 = function ( f10_arg0 )
					local f10_local0 = function ( f11_arg0 )
						local f11_local0 = function ( f12_arg0 )
							local f12_local0 = function ( f13_arg0 )
								f13_arg0:beginAnimation( 660 ) --[[ @ 0]]
								f13_arg0:setAlpha( 0 ) --[[ @ 0]]
								f13_arg0:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished ) --[[ @ 0]]
							end
							 --[[ @ 0]]
							f12_arg0:beginAnimation( 289 ) --[[ @ 0]]
							f12_arg0:registerEventHandler( "transition_complete_keyframe", f12_local0 ) --[[ @ 0]]
						end
						 --[[ @ 0]]
						f11_arg0:beginAnimation( 2300 ) --[[ @ 0]]
						f11_arg0:registerEventHandler( "transition_complete_keyframe", f11_local0 ) --[[ @ 0]]
					end
					 --[[ @ 0]]
					f10_arg0:beginAnimation( 940 ) --[[ @ 0]]
					f10_arg0:setAlpha( 1 ) --[[ @ 0]]
					f10_arg0:registerEventHandler( "transition_complete_keyframe", f10_local0 ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f8_arg0.Text:beginAnimation( 690 ) --[[ @ 0]]
				f8_arg0.Text:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted ) --[[ @ 0]]
				f8_arg0.Text:registerEventHandler( "transition_complete_keyframe", f9_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f8_arg0.Text:completeAnimation() --[[ @ 0]]
			f8_arg0.Text:setLeftRight( 0, 0, 0, 1920 ) --[[ @ 0]]
			f8_arg0.Text:setTopBottom( 0, 0, 114, 181 ) --[[ @ 0]]
			f8_arg0.Text:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.Text:setScale( 1, 1 ) --[[ @ 0]]
			f8_arg0.Text:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_5AB00E68B32F8B69" ) ) --[[ @ 0]]
			f8_local0( f8_arg0.Text ) --[[ @ 0]]
			local f8_local1 = function ( f14_arg0 )
				local f14_local0 = function ( f15_arg0 )
					local f15_local0 = function ( f16_arg0 )
						local f16_local0 = function ( f17_arg0 )
							local f17_local0 = function ( f18_arg0 )
								f18_arg0:beginAnimation( 909 ) --[[ @ 0]]
								f18_arg0:setAlpha( 0 ) --[[ @ 0]]
								f18_arg0:setScale( 1.8, 0.6 ) --[[ @ 0]]
								f18_arg0:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished ) --[[ @ 0]]
							end
							 --[[ @ 0]]
							f17_arg0:beginAnimation( 700 ) --[[ @ 0]]
							f17_arg0:setAlpha( 1 ) --[[ @ 0]]
							f17_arg0:setScale( 1.6, 0.9 ) --[[ @ 0]]
							f17_arg0:registerEventHandler( "transition_complete_keyframe", f17_local0 ) --[[ @ 0]]
						end
						 --[[ @ 0]]
						f16_arg0:beginAnimation( 640 ) --[[ @ 0]]
						f16_arg0:setAlpha( 0.2 ) --[[ @ 0]]
						f16_arg0:setScale( 1.59, 0.8 ) --[[ @ 0]]
						f16_arg0:registerEventHandler( "transition_complete_keyframe", f16_local0 ) --[[ @ 0]]
					end
					 --[[ @ 0]]
					f15_arg0:beginAnimation( 2310 ) --[[ @ 0]]
					f15_arg0:setAlpha( 0 ) --[[ @ 0]]
					f15_arg0:setScale( 1.57, 0.8 ) --[[ @ 0]]
					f15_arg0:registerEventHandler( "transition_complete_keyframe", f15_local0 ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f8_arg0.ZMTitleFog:beginAnimation( 690 ) --[[ @ 0]]
				f8_arg0.ZMTitleFog:setAlpha( 1 ) --[[ @ 0]]
				f8_arg0.ZMTitleFog:setScale( 1.5, 0.8 ) --[[ @ 0]]
				f8_arg0.ZMTitleFog:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted ) --[[ @ 0]]
				f8_arg0.ZMTitleFog:registerEventHandler( "transition_complete_keyframe", f14_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f8_arg0.ZMTitleFog:completeAnimation() --[[ @ 0]]
			f8_arg0.ZMTitleFog:setTopBottom( 0, 0, -103, 321 ) --[[ @ 0]]
			f8_arg0.ZMTitleFog:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.ZMTitleFog:setScale( 1.5, 0.6 ) --[[ @ 0]]
			f8_local1( f8_arg0.ZMTitleFog ) --[[ @ 0]]
		end
	},
	ItemAvailable = {
		DefaultClip = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties() --[[ @ 0]]
			f19_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			local f19_local0 = function ( f20_arg0 )
				local f20_local0 = function ( f21_arg0 )
					local f21_local0 = function ( f22_arg0 )
						local f22_local0 = function ( f23_arg0 )
							local f23_local0 = function ( f24_arg0 )
								f24_arg0:beginAnimation( 439 ) --[[ @ 0]]
								f24_arg0:setAlpha( 0 ) --[[ @ 0]]
								f24_arg0:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished ) --[[ @ 0]]
							end
							 --[[ @ 0]]
							f23_arg0:beginAnimation( 510 ) --[[ @ 0]]
							f23_arg0:registerEventHandler( "transition_complete_keyframe", f23_local0 ) --[[ @ 0]]
						end
						 --[[ @ 0]]
						f22_arg0:beginAnimation( 1270 ) --[[ @ 0]]
						f22_arg0:registerEventHandler( "transition_complete_keyframe", f22_local0 ) --[[ @ 0]]
					end
					 --[[ @ 0]]
					f21_arg0:beginAnimation( 1040 ) --[[ @ 0]]
					f21_arg0:setAlpha( 1 ) --[[ @ 0]]
					f21_arg0:registerEventHandler( "transition_complete_keyframe", f21_local0 ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f19_arg0.Text:beginAnimation( 1960 ) --[[ @ 0]]
				f19_arg0.Text:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted ) --[[ @ 0]]
				f19_arg0.Text:registerEventHandler( "transition_complete_keyframe", f20_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f19_arg0.Text:completeAnimation() --[[ @ 0]]
			f19_arg0.Text:setLeftRight( 0, 0, 0, 1920 ) --[[ @ 0]]
			f19_arg0.Text:setTopBottom( 0, 0, 114, 181 ) --[[ @ 0]]
			f19_arg0.Text:setAlpha( 0 ) --[[ @ 0]]
			f19_arg0.Text:setScale( 1, 1 ) --[[ @ 0]]
			f19_local0( f19_arg0.Text ) --[[ @ 0]]
			local f19_local1 = function ( f25_arg0 )
				local f25_local0 = function ( f26_arg0 )
					local f26_local0 = function ( f27_arg0 )
						local f27_local0 = function ( f28_arg0 )
							local f28_local0 = function ( f29_arg0 )
								f29_arg0:beginAnimation( 1619 ) --[[ @ 0]]
								f29_arg0:setAlpha( 0 ) --[[ @ 0]]
								f29_arg0:setScale( 1.8, 0.6 ) --[[ @ 0]]
								f29_arg0:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished ) --[[ @ 0]]
							end
							 --[[ @ 0]]
							f28_arg0:beginAnimation( 920 ) --[[ @ 0]]
							f28_arg0:setAlpha( 1 ) --[[ @ 0]]
							f28_arg0:setScale( 1.6, 0.9 ) --[[ @ 0]]
							f28_arg0:registerEventHandler( "transition_complete_keyframe", f28_local0 ) --[[ @ 0]]
						end
						 --[[ @ 0]]
						f27_arg0:beginAnimation( 980 ) --[[ @ 0]]
						f27_arg0:setAlpha( 0.2 ) --[[ @ 0]]
						f27_arg0:setScale( 1.59, 0.8 ) --[[ @ 0]]
						f27_arg0:registerEventHandler( "transition_complete_keyframe", f27_local0 ) --[[ @ 0]]
					end
					 --[[ @ 0]]
					f26_arg0:beginAnimation( 1730 ) --[[ @ 0]]
					f26_arg0:setAlpha( 0 ) --[[ @ 0]]
					f26_arg0:setScale( 1.56, 0.8 ) --[[ @ 0]]
					f26_arg0:registerEventHandler( "transition_complete_keyframe", f26_local0 ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f19_arg0.ZMTitleFog:beginAnimation( 1270 ) --[[ @ 0]]
				f19_arg0.ZMTitleFog:setAlpha( 1 ) --[[ @ 0]]
				f19_arg0.ZMTitleFog:setScale( 1.5, 0.8 ) --[[ @ 0]]
				f19_arg0.ZMTitleFog:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted ) --[[ @ 0]]
				f19_arg0.ZMTitleFog:registerEventHandler( "transition_complete_keyframe", f25_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f19_arg0.ZMTitleFog:completeAnimation() --[[ @ 0]]
			f19_arg0.ZMTitleFog:setTopBottom( 0, 0, -103, 321 ) --[[ @ 0]]
			f19_arg0.ZMTitleFog:setAlpha( 0 ) --[[ @ 0]]
			f19_arg0.ZMTitleFog:setScale( 1.5, 0.6 ) --[[ @ 0]]
			f19_local1( f19_arg0.ZMTitleFog ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.ZMTributeSplash.__onClose = function ( f30_arg0 )
	f30_arg0.ZMTitleFog:close() --[[ @ 0]]
end
 --[[ @ 0]]
