-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:35
CoD.MPWheelPrompt = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.MPWheelPrompt.__defaultWidth = 80 --[[ @ 0]]
CoD.MPWheelPrompt.__defaultHeight = 80 --[[ @ 0]]
CoD.MPWheelPrompt.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.MPWheelPrompt ) --[[ @ 0]]
	self.id = "MPWheelPrompt" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local RStick = LUI.UIImage.new( 0.5, 0.5, -40, 40, 0.5, 0.5, -40, 40 ) --[[ @ 0]]
	RStick:subscribeToGlobalModel( f1_arg1, "Controller", "move_right_stick_button_image", function ( model )
		local f2_local0 = model:get() --[[ @ 0]]
		if f2_local0 ~= nil then
			RStick:setImage( RegisterImage( f2_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( RStick ) --[[ @ 0]]
	self.RStick = RStick --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "Keyboard",
			condition = function ( menu, element, event )
				return IsMouseOrKeyboard( f1_arg1 )
			end
		}
	} ) --[[ @ 0]]
	self:appendEventHandler( "input_source_changed", function ( f4_arg0, f4_arg1 )
		f4_arg1.menu = f4_arg1.menu or f1_arg0 --[[ @ 0]]
		f1_arg0:updateElementState( self, f4_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	local f1_local2 = self --[[ @ 0]]
	local f1_local3 = self.subscribeToModel --[[ @ 0]]
	local f1_local4 = Engine[@"GetModelForController"]( f1_arg1 ) --[[ @ 0]]
	f1_local3( f1_local2, f1_local4.LastInput, function ( f5_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f5_arg0:get(),
			modelName = "LastInput"
		} ) --[[ @ 0]]
	end, false ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.MPWheelPrompt.__resetProperties = function ( f6_arg0 )
	f6_arg0.RStick:completeAnimation() --[[ @ 0]]
	f6_arg0.RStick:setAlpha( 1 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.MPWheelPrompt.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f7_arg0.RStick:completeAnimation() --[[ @ 0]]
			f7_arg0.RStick:setAlpha( 1 ) --[[ @ 0]]
			f7_arg0.clipFinished( f7_arg0.RStick ) --[[ @ 0]]
		end
	},
	Keyboard = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties() --[[ @ 0]]
			f8_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f8_arg0.RStick:completeAnimation() --[[ @ 0]]
			f8_arg0.RStick:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.clipFinished( f8_arg0.RStick ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.MPWheelPrompt.__onClose = function ( f9_arg0 )
	f9_arg0.RStick:close() --[[ @ 0]]
end
 --[[ @ 0]]
