-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:35
CoD.ZMInvSentinelArtifactLarge = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.ZMInvSentinelArtifactLarge.__defaultWidth = 384 --[[ @ 0]]
CoD.ZMInvSentinelArtifactLarge.__defaultHeight = 384 --[[ @ 0]]
CoD.ZMInvSentinelArtifactLarge.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.ZMInvSentinelArtifactLarge ) --[[ @ 0]]
	self.id = "ZMInvSentinelArtifactLarge" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local StageImage = LUI.UIImage.new( 0.17, 1.17, -64, -64, 0.17, 1.17, -64, -64 ) --[[ @ 0]]
	StageImage:setAlpha( 0 ) --[[ @ 0]]
	StageImage:linkToElementModel( self, "Ring.stage", true, function ( model )
		local f2_local0 = model:get() --[[ @ 0]]
		if f2_local0 ~= nil then
			StageImage:setImage( RegisterImage( CoD.ZMInventoryUtility.StageToSentinelImage( f2_local0 ) ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( StageImage ) --[[ @ 0]]
	self.StageImage = StageImage --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "ON",
			condition = function ( menu, element, event )
				return IsMapName( "zm_orange" ) and CoD.ZombieUtility.IsEasterEggsAllowed( f1_arg1 )
			end
		}
	} ) --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.ZMInvSentinelArtifactLarge.__resetProperties = function ( f4_arg0 )
	f4_arg0.StageImage:completeAnimation() --[[ @ 0]]
	f4_arg0.StageImage:setAlpha( 0 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.ZMInvSentinelArtifactLarge.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties() --[[ @ 0]]
			f5_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	ON = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties() --[[ @ 0]]
			f6_arg0:setupElementClipCounter( 1 ) --[[ @ 0]]
			f6_arg0.StageImage:completeAnimation() --[[ @ 0]]
			f6_arg0.StageImage:setAlpha( 1 ) --[[ @ 0]]
			f6_arg0.clipFinished( f6_arg0.StageImage ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.ZMInvSentinelArtifactLarge.__onClose = function ( f7_arg0 )
	f7_arg0.StageImage:close() --[[ @ 0]]
end
 --[[ @ 0]]
