-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:36
require( "ui/uieditor/widgets/gamesettings/gamesettings_texbox" ) --[[ @ 0]]
require( "ui/uieditor/widgets/gamesettings/gamesettings_titlesecbox" ) --[[ @ 0]]

local PostLoadFunc = function ( self, controller, menu )
	local f1_local0 = Engine[@"hash_5EA74FA7EE46E195"]( Engine[@"hash_169811927938FCD7"]() ) --[[ @ 0]]
	local f1_local1 = f1_local0.image --[[ @ 0]]
	local f1_local2 = f1_local0.nameRefCaps --[[ @ 0]]
	local f1_local3 = f1_local0.descriptionRef --[[ @ 0]]
	self.image:setImage( RegisterImage( f1_local1 ) ) --[[ @ 0]]
	local f1_local4 = self.GameSettingstexbox.TextBox --[[ @ 0]]
	local f1_local5 = f1_local4 --[[ @ 0]]
	f1_local4 = f1_local4.setText --[[ @ 0]]
	local f1_local6 --[[ @ 0]]
	if f1_local3 then
		f1_local6 = Engine[@"hash_4F9F1239CFD921FE"]( f1_local3 ) --[[ @ 0]]
		if not f1_local6 then
		
		else
			f1_local4( f1_local5, f1_local6 ) --[[ @ 0]]
			f1_local4 = self.GameSettingstitlesecbox.Textbox --[[ @ 0]]
			f1_local5 = f1_local4 --[[ @ 0]]
			f1_local4 = f1_local4.setText --[[ @ 0]]
			if f1_local2 then
				f1_local6 = Engine[@"hash_4F9F1239CFD921FE"]( f1_local2 ) --[[ @ 0]]
				if not f1_local6 then
				
				else
					f1_local4( f1_local5, f1_local6 ) --[[ @ 0]]
				end
			end
			f1_local6 = "" --[[ @ 0]]
		end
	end
	f1_local6 = "" --[[ @ 0]]
end
 --[[ @ 0]]
CoD.GameSettings_MatchSettingsInfo = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.GameSettings_MatchSettingsInfo.__defaultWidth = 674 --[[ @ 0]]
CoD.GameSettings_MatchSettingsInfo.__defaultHeight = 115 --[[ @ 0]]
CoD.GameSettings_MatchSettingsInfo.new = function ( f2_arg0, f2_arg1, f2_arg2, f2_arg3, f2_arg4, f2_arg5, f2_arg6, f2_arg7, f2_arg8, f2_arg9 )
	local self = LUI.UIElement.new( f2_arg2, f2_arg3, f2_arg4, f2_arg5, f2_arg6, f2_arg7, f2_arg8, f2_arg9 ) --[[ @ 0]]
	self:setClass( CoD.GameSettings_MatchSettingsInfo ) --[[ @ 0]]
	self.id = "GameSettings_MatchSettingsInfo" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	
	local image = LUI.UIImage.new( 0, 0, 0, 115, 1, 1, -115, 0 ) --[[ @ 0]]
	image:setImage( RegisterImage( @"playlist_war" ) ) --[[ @ 0]]
	self:addElement( image ) --[[ @ 0]]
	self.image = image --[[ @ 0]]
	
	local GameSettingstitlesecbox = CoD.GameSettings_titlesecbox.new( f2_arg0, f2_arg1, 1, 1, -549, 0, 0, 0, 0, 42 ) --[[ @ 0]]
	GameSettingstitlesecbox:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	GameSettingstitlesecbox:subscribeToGlobalModel( f2_arg1, "GametypeSettings", "gametype", function ( model )
		local f3_local0 = model:get() --[[ @ 0]]
		if f3_local0 ~= nil then
			GameSettingstitlesecbox.Textbox:setText( LocalizeToUpperString( f3_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( GameSettingstitlesecbox ) --[[ @ 0]]
	self.GameSettingstitlesecbox = GameSettingstitlesecbox --[[ @ 0]]
	
	local GameSettingstexbox = CoD.GameSettings_texbox.new( f2_arg0, f2_arg1, 1, 1, -549, 0, 0, 0, 42, 115 ) --[[ @ 0]]
	GameSettingstexbox.TextBox:setAlpha( 0.15 ) --[[ @ 0]]
	GameSettingstexbox.TextBox:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_750499BB4CC7AF75" ) ) --[[ @ 0]]
	self:addElement( GameSettingstexbox ) --[[ @ 0]]
	self.GameSettingstexbox = GameSettingstexbox --[[ @ 0]]
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f2_arg1, f2_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.GameSettings_MatchSettingsInfo.__onClose = function ( f4_arg0 )
	f4_arg0.GameSettingstitlesecbox:close() --[[ @ 0]]
	f4_arg0.GameSettingstexbox:close() --[[ @ 0]]
end
 --[[ @ 0]]
