-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:51
CoD.Social_NoFriends = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.Social_NoFriends.__defaultWidth = 1920 --[[ @ 0]]
CoD.Social_NoFriends.__defaultHeight = 1080 --[[ @ 0]]
CoD.Social_NoFriends.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.Social_NoFriends ) --[[ @ 0]]
	self.id = "Social_NoFriends" --[[ @ 0]]
	self.soundSet = "ChooseDecal" --[[ @ 0]]
	
	local noFriends = LUI.UIText.new( 0, 0, 210, 1710, 0, 0, 526, 554 ) --[[ @ 0]]
	noFriends:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b ) --[[ @ 0]]
	noFriends:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_BAA9A79FE50F45E" ) ) --[[ @ 0]]
	noFriends:setTTF( "dinnext_regular" ) --[[ @ 0]]
	noFriends:setLetterSpacing( 3 ) --[[ @ 0]]
	noFriends:setLineSpacing( 8 ) --[[ @ 0]]
	noFriends:setAlignment( Enum[@"luialignment"][@"lui_alignment_center"] ) --[[ @ 0]]
	noFriends:setAlignment( Enum[@"luialignment"][@"lui_alignment_top"] ) --[[ @ 0]]
	self:addElement( noFriends ) --[[ @ 0]]
	self.noFriends = noFriends --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
