-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:51
CoD.SeparationLine_Vertical = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.SeparationLine_Vertical.__defaultWidth = 1 --[[ @ 0]]
CoD.SeparationLine_Vertical.__defaultHeight = 61 --[[ @ 0]]
CoD.SeparationLine_Vertical.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.SeparationLine_Vertical ) --[[ @ 0]]
	self.id = "SeparationLine_Vertical" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	
	local DotT = LUI.UIImage.new( 0, 0, 0, 1, 0, 0, 0, 1 ) --[[ @ 0]]
	DotT:setAlpha( 0.3 ) --[[ @ 0]]
	self:addElement( DotT ) --[[ @ 0]]
	self.DotT = DotT --[[ @ 0]]
	
	local DotB = LUI.UIImage.new( 0, 0, 0, 1, 1, 1, -1, 0 ) --[[ @ 0]]
	DotB:setAlpha( 0.3 ) --[[ @ 0]]
	self:addElement( DotB ) --[[ @ 0]]
	self.DotB = DotB --[[ @ 0]]
	
	local Line = LUI.UIImage.new( 0, 0, 0, 1, 0, 1, 0, 0 ) --[[ @ 0]]
	Line:setRGB( 0.38, 0.36, 0.33 ) --[[ @ 0]]
	Line:setAlpha( 0.3 ) --[[ @ 0]]
	self:addElement( Line ) --[[ @ 0]]
	self.Line = Line --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
