-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:51
require( "ui/uieditor/widgets/fe_nat" ) --[[ @ 0]]
require( "ui/uieditor/widgets/footer/fe_leftcontainer_notlobby" ) --[[ @ 0]]
require( "ui/uieditor/widgets/footer/fe_rightcontainerwithheroeshead" ) --[[ @ 0]]
require( "ui/uieditor/widgets/footer/fe_rightcontainerwithoutrightboxes" ) --[[ @ 0]]

CoD.fe_FooterContainer_NOTLobby = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.fe_FooterContainer_NOTLobby.__defaultWidth = 1920 --[[ @ 0]]
CoD.fe_FooterContainer_NOTLobby.__defaultHeight = 97 --[[ @ 0]]
CoD.fe_FooterContainer_NOTLobby.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.fe_FooterContainer_NOTLobby ) --[[ @ 0]]
	self.id = "fe_FooterContainer_NOTLobby" --[[ @ 0]]
	self.soundSet = "default" --[[ @ 0]]
	self.onlyChildrenFocusable = CoD.isPC --[[ @ 0]]
	self.anyChildUsesUpdateState = true --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local feNAT = CoD.fe_NAT.new( f1_arg0, f1_arg1, 1, 1, -265, -93, 1, 1, -124, -85 ) --[[ @ 0]]
	feNAT:setAlpha( 0 ) --[[ @ 0]]
	self:addElement( feNAT ) --[[ @ 0]]
	self.feNAT = feNAT --[[ @ 0]]
	
	local feLeftContainer = CoD.fe_LeftContainer_NOTLobby.new( f1_arg0, f1_arg1, 0, 0, 23, 825, 1, 1, -72, -6 ) --[[ @ 0]]
	feLeftContainer:linkToElementModel( self, nil, false, function ( model )
		feLeftContainer:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( feLeftContainer ) --[[ @ 0]]
	self.feLeftContainer = feLeftContainer --[[ @ 0]]
	
	local feRightContainerWithoutRightBoxes0 = CoD.fe_RightContainerWithoutRightBoxes.new( f1_arg0, f1_arg1, 1, 1, -1352.5, -47.5, 1, 1, -54, -10 ) --[[ @ 0]]
	feRightContainerWithoutRightBoxes0:linkToElementModel( self, nil, false, function ( model )
		feRightContainerWithoutRightBoxes0:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( feRightContainerWithoutRightBoxes0 ) --[[ @ 0]]
	self.feRightContainerWithoutRightBoxes0 = feRightContainerWithoutRightBoxes0 --[[ @ 0]]
	
	local feRightContainerWithHeroesHead = CoD.fe_RightContainerWithHeroesHead.new( f1_arg0, f1_arg1, 1, 1, -1279.5, 25.5, 1, 1, -58, -10 ) --[[ @ 0]]
	feRightContainerWithHeroesHead:setAlpha( 0 ) --[[ @ 0]]
	feRightContainerWithHeroesHead:linkToElementModel( self, nil, false, function ( model )
		feRightContainerWithHeroesHead:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( feRightContainerWithHeroesHead ) --[[ @ 0]]
	self.feRightContainerWithHeroesHead = feRightContainerWithHeroesHead --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "WithHeroesHead",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		}
	} ) --[[ @ 0]]
	if CoD.isPC then
		feLeftContainer.id = "feLeftContainer" --[[ @ 0]]
	end
	if CoD.isPC then
		feRightContainerWithoutRightBoxes0.id = "feRightContainerWithoutRightBoxes0" --[[ @ 0]]
	end
	if CoD.isPC then
		feRightContainerWithHeroesHead.id = "feRightContainerWithHeroesHead" --[[ @ 0]]
	end
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.fe_FooterContainer_NOTLobby.__resetProperties = function ( f6_arg0 )
	f6_arg0.feRightContainerWithHeroesHead:completeAnimation() --[[ @ 0]]
	f6_arg0.feRightContainerWithoutRightBoxes0:completeAnimation() --[[ @ 0]]
	f6_arg0.feRightContainerWithHeroesHead:setLeftRight( 1, 1, -1279.5, 25.5 ) --[[ @ 0]]
	f6_arg0.feRightContainerWithHeroesHead:setTopBottom( 1, 1, -58, -10 ) --[[ @ 0]]
	f6_arg0.feRightContainerWithHeroesHead:setAlpha( 0 ) --[[ @ 0]]
	f6_arg0.feRightContainerWithoutRightBoxes0:setAlpha( 1 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.fe_FooterContainer_NOTLobby.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties() --[[ @ 0]]
			f7_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	WithHeroesHead = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties() --[[ @ 0]]
			f8_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f8_arg0.feRightContainerWithoutRightBoxes0:completeAnimation() --[[ @ 0]]
			f8_arg0.feRightContainerWithoutRightBoxes0:setAlpha( 0 ) --[[ @ 0]]
			f8_arg0.clipFinished( f8_arg0.feRightContainerWithoutRightBoxes0 ) --[[ @ 0]]
			f8_arg0.feRightContainerWithHeroesHead:completeAnimation() --[[ @ 0]]
			f8_arg0.feRightContainerWithHeroesHead:setLeftRight( 1, 1, -1040.5, 264.5 ) --[[ @ 0]]
			f8_arg0.feRightContainerWithHeroesHead:setTopBottom( 1, 1, -58, -10 ) --[[ @ 0]]
			f8_arg0.feRightContainerWithHeroesHead:setAlpha( 1 ) --[[ @ 0]]
			f8_arg0.clipFinished( f8_arg0.feRightContainerWithHeroesHead ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.fe_FooterContainer_NOTLobby.__onClose = function ( f9_arg0 )
	f9_arg0.feNAT:close() --[[ @ 0]]
	f9_arg0.feLeftContainer:close() --[[ @ 0]]
	f9_arg0.feRightContainerWithoutRightBoxes0:close() --[[ @ 0]]
	f9_arg0.feRightContainerWithHeroesHead:close() --[[ @ 0]]
end
 --[[ @ 0]]
