-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 20-02-2025 19:36
require( "ui/uieditor/widgets/emptyfocusable" ) --[[ @ 0]]
require( "x64:4aed1ac7f246af18" ) --[[ @ 0]]
require( "x64:3baff2229992d7b6" ) --[[ @ 0]]

CoD.PC_SimpleVScrollList = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.PC_SimpleVScrollList.__defaultWidth = 1007 --[[ @ 0]]
CoD.PC_SimpleVScrollList.__defaultHeight = 1080 --[[ @ 0]]
CoD.PC_SimpleVScrollList.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	self:setClass( CoD.PC_SimpleVScrollList ) --[[ @ 0]]
	self.id = "PC_SimpleVScrollList" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	self.onlyChildrenFocusable = true --[[ @ 0]]
	self.anyChildUsesUpdateState = true --[[ @ 0]]
	
	local emptyFocusable = CoD.emptyFocusable.new( f1_arg0, f1_arg1, 0, 1.03, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	self:addElement( emptyFocusable ) --[[ @ 0]]
	self.emptyFocusable = emptyFocusable --[[ @ 0]]
	
	local ScrollView = CoD.PC_SimpleVScrollList_List.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 ) --[[ @ 0]]
	self:addElement( ScrollView ) --[[ @ 0]]
	self.ScrollView = ScrollView --[[ @ 0]]
	
	local VScrollbar = CoD.PC_VScrollbar.new( f1_arg0, f1_arg1, 1, 1, 2, 16, 0, 1, 0, 0 ) --[[ @ 0]]
	self:addElement( VScrollbar ) --[[ @ 0]]
	self.VScrollbar = VScrollbar --[[ @ 0]]
	
	self:subscribeToGlobalModel( f1_arg1, "PerController", "scriptNotify", function ( model )
		local f2_local0 = self --[[ @ 0]]
		if CoD.ModelUtility.IsParamModelEqualToHashString( model, @"hash_7C72FFE9CF2F9FFA" ) then
			CoD.PCWidgetUtility.ScrollUpDown( self, f1_arg1, f1_arg0, model ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	emptyFocusable.id = "emptyFocusable" --[[ @ 0]]
	ScrollView.id = "ScrollView" --[[ @ 0]]
	VScrollbar.id = "VScrollbar" --[[ @ 0]]
	self.__defaultFocus = ScrollView --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	local f1_local4 = self --[[ @ 0]]
	CoD.PCWidgetUtility.PrepareSimpleVScrollWidget( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	CoD.PCUtility.SetForceMouseEventDispatch( self, true ) --[[ @ 0]]
	DisableKeyboardNavigationByElement( self.emptyFocusable ) --[[ @ 0]]
	return self
end
 --[[ @ 0]]
CoD.PC_SimpleVScrollList.__onClose = function ( f3_arg0 )
	f3_arg0.emptyFocusable:close() --[[ @ 0]]
	f3_arg0.ScrollView:close() --[[ @ 0]]
	f3_arg0.VScrollbar:close() --[[ @ 0]]
end
 --[[ @ 0]]
