-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-02-2025 19:51
require( "ui/uieditor/widgets/aar_t8/levelup/aarxpmeter" ) --[[ @ 0]]
require( "x64:5ffa4895b0d22816" ) --[[ @ 0]]
require( "x64:3117670e09bbb2dc" ) --[[ @ 0]]
require( "x64:7a5b6deff4bc3cab" ) --[[ @ 0]]
require( "ui/uieditor/widgets/aar_t8/summary/aargameinfo" ) --[[ @ 0]]
require( "x64:382f04d17b42755f" ) --[[ @ 0]]
require( "x64:ca5faac82324b65" ) --[[ @ 0]]
require( "x64:c96de52191fe142" ) --[[ @ 0]]
require( "x64:5df1637f3c8cfb9c" ) --[[ @ 0]]
require( "x64:41ff27ba8f489b41" ) --[[ @ 0]]
require( "x64:6f52167eaf5dc054" ) --[[ @ 0]]

CoD.AARSummaryTabInternal = InheritFrom( LUI.UIElement ) --[[ @ 0]]
CoD.AARSummaryTabInternal.__defaultWidth = 1920 --[[ @ 0]]
CoD.AARSummaryTabInternal.__defaultHeight = 900 --[[ @ 0]]
CoD.AARSummaryTabInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 ) --[[ @ 0]]
	if IsZombies() then
		CoD.ZombieUtility.AdjustAarAllTimeStatWidgetsWidthToStretchAcrossMapImage( f1_arg0, f1_arg1, 2, 4 ) --[[ @ 0]]
		CoD.ZombieUtility.AdjustAarStatWidgetsWidthToStretchAcrossMapImage( f1_arg0, f1_arg1, 14, 2 ) --[[ @ 0]]
	end
	self:setClass( CoD.AARSummaryTabInternal ) --[[ @ 0]]
	self.id = "AARSummaryTabInternal" --[[ @ 0]]
	self.soundSet = "none" --[[ @ 0]]
	self.onlyChildrenFocusable = CoD.isPC --[[ @ 0]]
	self.anyChildUsesUpdateState = true --[[ @ 0]]
	f1_arg0:addElementToPendingUpdateStateList( self ) --[[ @ 0]]
	
	local AARTierBar = CoD.AARTierBar.new( f1_arg0, f1_arg1, 0, 0, 797, 1639, 0, 0, 732, 752 ) --[[ @ 0]]
	AARTierBar:mergeStateConditions( {
		{
			stateName = "Hidden",
			condition = function ( menu, element, event )
				return CoD.AARUtility.ShouldHideTierRewardMiniStatus( self, f1_arg1 )
			end
		}
	} ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "tierProgress", true, function ( model )
		local f3_local0 = model:get() --[[ @ 0]]
		if f3_local0 ~= nil then
			AARTierBar.EarnedXP.Meter:setShaderVector( 0, CoD.GetVectorComponentFromString( f3_local0, 1 ), CoD.GetVectorComponentFromString( f3_local0, 2 ), CoD.GetVectorComponentFromString( f3_local0, 3 ), CoD.GetVectorComponentFromString( f3_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "tierProgress", true, function ( model )
		local f4_local0 = model:get() --[[ @ 0]]
		if f4_local0 ~= nil then
			AARTierBar.EarnedXP.MeterAdd:setShaderVector( 0, CoD.GetVectorComponentFromString( f4_local0, 1 ), CoD.GetVectorComponentFromString( f4_local0, 2 ), CoD.GetVectorComponentFromString( f4_local0, 3 ), CoD.GetVectorComponentFromString( f4_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "tierProgress", true, function ( model )
		local f5_local0 = model:get() --[[ @ 0]]
		if f5_local0 ~= nil then
			AARTierBar.EarnedXP.MeterGlow:setShaderVector( 0, CoD.GetVectorComponentFromString( f5_local0, 1 ), CoD.GetVectorComponentFromString( f5_local0, 2 ), CoD.GetVectorComponentFromString( f5_local0, 3 ), CoD.GetVectorComponentFromString( f5_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "previousTierProgress", true, function ( model )
		local f6_local0 = model:get() --[[ @ 0]]
		if f6_local0 ~= nil then
			AARTierBar.PreviousXP.Meter:setShaderVector( 0, CoD.GetVectorComponentFromString( f6_local0, 1 ), CoD.GetVectorComponentFromString( f6_local0, 2 ), CoD.GetVectorComponentFromString( f6_local0, 3 ), CoD.GetVectorComponentFromString( f6_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "previousTierProgress", true, function ( model )
		local f7_local0 = model:get() --[[ @ 0]]
		if f7_local0 ~= nil then
			AARTierBar.PreviousXP.MeterAdd:setShaderVector( 0, CoD.GetVectorComponentFromString( f7_local0, 1 ), CoD.GetVectorComponentFromString( f7_local0, 2 ), CoD.GetVectorComponentFromString( f7_local0, 3 ), CoD.GetVectorComponentFromString( f7_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "previousTierProgress", true, function ( model )
		local f8_local0 = model:get() --[[ @ 0]]
		if f8_local0 ~= nil then
			AARTierBar.PreviousXP.MeterGlow:setShaderVector( 0, CoD.GetVectorComponentFromString( f8_local0, 1 ), CoD.GetVectorComponentFromString( f8_local0, 2 ), CoD.GetVectorComponentFromString( f8_local0, 3 ), CoD.GetVectorComponentFromString( f8_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "barCurrentTier", true, function ( model )
		local f9_local0 = model:get() --[[ @ 0]]
		if f9_local0 ~= nil then
			AARTierBar.CurrentTier:setText( LocalizeStringWithParameter( @"hash_1E743A7E5D0C37CD", f9_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	AARTierBar:linkToElementModel( self, "barNextTier", true, function ( model )
		local f10_local0 = model:get() --[[ @ 0]]
		if f10_local0 ~= nil then
			AARTierBar.NextTier:setText( LocalizeStringWithParameter( @"hash_1E743A7E5D0C37CD", f10_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( AARTierBar ) --[[ @ 0]]
	self.AARTierBar = AARTierBar --[[ @ 0]]
	
	local XPMeter = CoD.AARXpMeter.new( f1_arg0, f1_arg1, 0.5, 0.5, -620, 680, 0, 0, 684, 704 ) --[[ @ 0]]
	XPMeter:mergeStateConditions( {
		{
			stateName = "Hidden",
			condition = function ( menu, element, event )
				return not IsPublicOnlineGame()
			end
		},
		{
			stateName = "MaxRank",
			condition = function ( menu, element, event )
				local f12_local0 --[[ @ 0]]
				if not IsMaxPrestigeLevel( f1_arg1 ) then
					f12_local0 = CoD.ModelUtility.IsSelfModelValueGreaterThanOrEqualTo( element, f1_arg1, "rank", CoD.RankUtility.GetRankCap() ) --[[ @ 0]]
					if f12_local0 then
						f12_local0 = CoD.ModelUtility.IsSelfModelValueNilOrZero( element, f1_arg1, "xpNeededToLevelUp" ) --[[ @ 0]]
					end
				else
					f12_local0 = false --[[ @ 0]]
				end
				return f12_local0
			end
		},
		{
			stateName = "MaxParagonRank",
			condition = function ( menu, element, event )
				local f13_local0 = IsInParagonCapableGameMode() --[[ @ 0]]
				if f13_local0 then
					f13_local0 = IsMaxPrestigeLevel( f1_arg1 ) --[[ @ 0]]
					if f13_local0 then
						f13_local0 = CoD.ModelUtility.IsSelfModelValueGreaterThan( element, f1_arg1, "rank", CoD.RankUtility.GetParagonRankCap() ) --[[ @ 0]]
					end
				end
				return f13_local0
			end
		}
	} ) --[[ @ 0]]
	XPMeter:linkToElementModel( XPMeter, "rank", true, function ( model )
		f1_arg0:updateElementState( XPMeter, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "rank"
		} ) --[[ @ 0]]
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( XPMeter, "xpNeededToLevelUp", true, function ( model )
		f1_arg0:updateElementState( XPMeter, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "xpNeededToLevelUp"
		} ) --[[ @ 0]]
	end ) --[[ @ 0]]
	XPMeter.maxRankText:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"menu/max_level" ) ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, nil, false, function ( model )
		XPMeter:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "levelProgress", true, function ( model )
		local f17_local0 = model:get() --[[ @ 0]]
		if f17_local0 ~= nil then
			XPMeter.EarnedXP.Meter:setShaderVector( 0, CoD.GetVectorComponentFromString( f17_local0, 1 ), CoD.GetVectorComponentFromString( f17_local0, 2 ), CoD.GetVectorComponentFromString( f17_local0, 3 ), CoD.GetVectorComponentFromString( f17_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "levelProgress", true, function ( model )
		local f18_local0 = model:get() --[[ @ 0]]
		if f18_local0 ~= nil then
			XPMeter.EarnedXP.MeterAdd:setShaderVector( 0, CoD.GetVectorComponentFromString( f18_local0, 1 ), CoD.GetVectorComponentFromString( f18_local0, 2 ), CoD.GetVectorComponentFromString( f18_local0, 3 ), CoD.GetVectorComponentFromString( f18_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "levelProgress", true, function ( model )
		local f19_local0 = model:get() --[[ @ 0]]
		if f19_local0 ~= nil then
			XPMeter.EarnedXP.MeterGlow:setShaderVector( 0, CoD.GetVectorComponentFromString( f19_local0, 1 ), CoD.GetVectorComponentFromString( f19_local0, 2 ), CoD.GetVectorComponentFromString( f19_local0, 3 ), CoD.GetVectorComponentFromString( f19_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "previousProgressThisLevel", true, function ( model )
		local f20_local0 = model:get() --[[ @ 0]]
		if f20_local0 ~= nil then
			XPMeter.PreviousXP.Meter:setShaderVector( 0, CoD.GetVectorComponentFromString( f20_local0, 1 ), CoD.GetVectorComponentFromString( f20_local0, 2 ), CoD.GetVectorComponentFromString( f20_local0, 3 ), CoD.GetVectorComponentFromString( f20_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "previousProgressThisLevel", true, function ( model )
		local f21_local0 = model:get() --[[ @ 0]]
		if f21_local0 ~= nil then
			XPMeter.PreviousXP.MeterAdd:setShaderVector( 0, CoD.GetVectorComponentFromString( f21_local0, 1 ), CoD.GetVectorComponentFromString( f21_local0, 2 ), CoD.GetVectorComponentFromString( f21_local0, 3 ), CoD.GetVectorComponentFromString( f21_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "previousProgressThisLevel", true, function ( model )
		local f22_local0 = model:get() --[[ @ 0]]
		if f22_local0 ~= nil then
			XPMeter.PreviousXP.MeterGlow:setShaderVector( 0, CoD.GetVectorComponentFromString( f22_local0, 1 ), CoD.GetVectorComponentFromString( f22_local0, 2 ), CoD.GetVectorComponentFromString( f22_local0, 3 ), CoD.GetVectorComponentFromString( f22_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "xpEarnedDuringMatch", true, function ( model )
		local f23_local0 = model:get() --[[ @ 0]]
		if f23_local0 ~= nil then
			XPMeter.xpEarnedText:setText( LocalizeIntoString( @"hash_75C4E2BA06EA49A5", f23_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	XPMeter:linkToElementModel( self, "xpNeededToLevelUp", true, function ( model )
		local f24_local0 = model:get() --[[ @ 0]]
		if f24_local0 ~= nil then
			XPMeter.xpNeededText:setText( CoD.RankUtility.GetNextRankXPStringLong( f24_local0 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( XPMeter ) --[[ @ 0]]
	self.XPMeter = XPMeter --[[ @ 0]]
	
	local AARGameHistory = CoD.AARGameHistory.new( f1_arg0, f1_arg1, 0, 0, 636.5, 1796.5, 0, 0, 366, 666 ) --[[ @ 0]]
	AARGameHistory:linkToElementModel( self, nil, false, function ( model )
		AARGameHistory:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( AARGameHistory ) --[[ @ 0]]
	self.AARGameHistory = AARGameHistory --[[ @ 0]]
	
	local AAREnemiesKIAWidget = CoD.AAREnemiesKIAWidget.new( f1_arg0, f1_arg1, 0, 0, 1461, 1801, 0, 0, 135.5, 267.5 ) --[[ @ 0]]
	AAREnemiesKIAWidget:linkToElementModel( self, nil, false, function ( model )
		AAREnemiesKIAWidget:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( AAREnemiesKIAWidget ) --[[ @ 0]]
	self.AAREnemiesKIAWidget = AAREnemiesKIAWidget --[[ @ 0]]
	
	local AARDamageWidget = CoD.AARDamageWidget.new( f1_arg0, f1_arg1, 0, 0, 1048.5, 1388.5, 0, 0, 135.5, 267.5 ) --[[ @ 0]]
	AARDamageWidget:linkToElementModel( self, nil, false, function ( model )
		AARDamageWidget:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( AARDamageWidget ) --[[ @ 0]]
	self.AARDamageWidget = AARDamageWidget --[[ @ 0]]
	
	local AARScoreWidget = CoD.AARScoreWidget.new( f1_arg0, f1_arg1, 0, 0, 636.5, 976.5, 0, 0, 135.5, 267.5 ) --[[ @ 0]]
	AARScoreWidget:linkToElementModel( self, nil, false, function ( model )
		AARScoreWidget:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( AARScoreWidget ) --[[ @ 0]]
	self.AARScoreWidget = AARScoreWidget --[[ @ 0]]
	
	local PerformanceLabel = LUI.UIText.new( 0, 0, 638.5, 1493.5, 0, 0, 91, 129 ) --[[ @ 0]]
	PerformanceLabel:setRGB( 0.9, 0.89, 0.78 ) --[[ @ 0]]
	PerformanceLabel:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_704B072C59118316" ) ) --[[ @ 0]]
	PerformanceLabel:setTTF( "ttmussels_demibold" ) --[[ @ 0]]
	PerformanceLabel:setLetterSpacing( 10 ) --[[ @ 0]]
	PerformanceLabel:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
	PerformanceLabel:setAlignment( Enum[@"luialignment"][@"lui_alignment_top"] ) --[[ @ 0]]
	self:addElement( PerformanceLabel ) --[[ @ 0]]
	self.PerformanceLabel = PerformanceLabel --[[ @ 0]]
	
	local AARGameInfo = CoD.AARGameInfo.new( f1_arg0, f1_arg1, 0, 0, 0, 1920, 0, 0, -21, 179 ) --[[ @ 0]]
	AARGameInfo:linkToElementModel( self, nil, false, function ( model )
		AARGameInfo:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( AARGameInfo ) --[[ @ 0]]
	self.AARGameInfo = AARGameInfo --[[ @ 0]]
	
	local ZmAllTimePerf = CoD.ZMAARAllTimePerfWidget.new( f1_arg0, f1_arg1, 0, 0, 638.5, 1803.5, 0, 0, 306, 712 ) --[[ @ 0]]
	ZmAllTimePerf:setAlpha( 0 ) --[[ @ 0]]
	ZmAllTimePerf:linkToElementModel( self, nil, false, function ( model )
		ZmAllTimePerf:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( ZmAllTimePerf ) --[[ @ 0]]
	self.ZmAllTimePerf = ZmAllTimePerf --[[ @ 0]]
	
	local ZmGenericSummaryList = LUI.GridLayout.new( f1_arg0, f1_arg1, false, 0, 0, 14, 0, nil, nil, false, false, false, false ) --[[ @ 0]]
	ZmGenericSummaryList:setLeftRight( 0, 0, 638.5, 1800.5 ) --[[ @ 0]]
	ZmGenericSummaryList:setTopBottom( 0, 0, 128.5, 272.5 ) --[[ @ 0]]
	ZmGenericSummaryList:setAlpha( 0 ) --[[ @ 0]]
	ZmGenericSummaryList:setAutoScaleContent( true ) --[[ @ 0]]
	ZmGenericSummaryList:setWidgetType( CoD.ZMGenericSummaryStatWidget ) --[[ @ 0]]
	ZmGenericSummaryList:setHorizontalCount( 6 ) --[[ @ 0]]
	ZmGenericSummaryList:setSpacing( 14 ) --[[ @ 0]]
	ZmGenericSummaryList:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
	ZmGenericSummaryList:setDataSource( "ZMSummaryListGeneric" ) --[[ @ 0]]
	self:addElement( ZmGenericSummaryList ) --[[ @ 0]]
	self.ZmGenericSummaryList = ZmGenericSummaryList --[[ @ 0]]
	
	local ZMPerformanceLabel = LUI.UIText.new( 0, 0, 635.5, 1490.5, 0, 0, 87, 125 ) --[[ @ 0]]
	ZMPerformanceLabel:setRGB( 0.9, 0.89, 0.78 ) --[[ @ 0]]
	ZMPerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
	ZMPerformanceLabel:setText( Engine[@"hash_4F9F1239CFD921FE"]( @"hash_704B072C59118316" ) ) --[[ @ 0]]
	ZMPerformanceLabel:setTTF( "skorzhen" ) --[[ @ 0]]
	ZMPerformanceLabel:setLetterSpacing( 10 ) --[[ @ 0]]
	ZMPerformanceLabel:setAlignment( Enum[@"luialignment"][@"lui_alignment_left"] ) --[[ @ 0]]
	ZMPerformanceLabel:setAlignment( Enum[@"luialignment"][@"lui_alignment_top"] ) --[[ @ 0]]
	self:addElement( ZMPerformanceLabel ) --[[ @ 0]]
	self.ZMPerformanceLabel = ZMPerformanceLabel --[[ @ 0]]
	
	local ZMAARGameInfo = CoD.ZMAARGameInfo.new( f1_arg0, f1_arg1, 0, 0, 615, 1589, 0, 0, -45, 68 ) --[[ @ 0]]
	ZMAARGameInfo:setAlpha( 0 ) --[[ @ 0]]
	ZMAARGameInfo:linkToElementModel( self, nil, false, function ( model )
		ZMAARGameInfo:setModel( model, f1_arg1 ) --[[ @ 0]]
	end ) --[[ @ 0]]
	self:addElement( ZMAARGameInfo ) --[[ @ 0]]
	self.ZMAARGameInfo = ZMAARGameInfo --[[ @ 0]]
	
	local LootCaseMeter = CoD.AARTierRewardLootCaseMeter.new( f1_arg0, f1_arg1, 0.5, 0.5, 693.5, 843.5, 0, 0, -25, 125 ) --[[ @ 0]]
	LootCaseMeter:linkToElementModel( self, "lootCaseProgress", true, function ( model )
		local f32_local0 = model:get() --[[ @ 0]]
		if f32_local0 ~= nil then
			LootCaseMeter.CurrentProgressRing:setShaderVector( 0, CoD.GetVectorComponentFromString( f32_local0, 1 ), CoD.GetVectorComponentFromString( f32_local0, 2 ), CoD.GetVectorComponentFromString( f32_local0, 3 ), CoD.GetVectorComponentFromString( f32_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	LootCaseMeter:linkToElementModel( self, "previousLootCaseProgress", true, function ( model )
		local f33_local0 = model:get() --[[ @ 0]]
		if f33_local0 ~= nil then
			LootCaseMeter.PreviousProgressRing:setShaderVector( 0, CoD.GetVectorComponentFromString( f33_local0, 1 ), CoD.GetVectorComponentFromString( f33_local0, 2 ), CoD.GetVectorComponentFromString( f33_local0, 3 ), CoD.GetVectorComponentFromString( f33_local0, 4 ) ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	LootCaseMeter:linkToElementModel( self, "lootCaseCount", true, function ( model )
		local f34_local0 = model:get() --[[ @ 0]]
		if f34_local0 ~= nil then
			LootCaseMeter.CaseCount:setText( f34_local0 ) --[[ @ 0]]
		end
	end ) --[[ @ 0]]
	self:addElement( LootCaseMeter ) --[[ @ 0]]
	self.LootCaseMeter = LootCaseMeter --[[ @ 0]]
	
	self:mergeStateConditions( {
		{
			stateName = "ShowMp_PC",
			condition = function ( menu, element, event )
				local f35_local0 --[[ @ 0]]
				if not IsZombies() then
					f35_local0 = IsPC() --[[ @ 0]]
				else
					f35_local0 = false --[[ @ 0]]
				end
				return f35_local0
			end
		},
		{
			stateName = "ShowZm_PC",
			condition = function ( menu, element, event )
				return IsZombies() and IsPC()
			end
		},
		{
			stateName = "DefaultState_PC",
			condition = function ( menu, element, event )
				return IsPC()
			end
		},
		{
			stateName = "ShowMp",
			condition = function ( menu, element, event )
				return not IsZombies()
			end
		},
		{
			stateName = "ShowZm",
			condition = function ( menu, element, event )
				return IsZombies()
			end
		}
	} ) --[[ @ 0]]
	local f1_local14 = self --[[ @ 0]]
	local f1_local15 = self.subscribeToModel --[[ @ 0]]
	local f1_local16 = Engine[@"getglobalmodel"]() --[[ @ 0]]
	f1_local15( f1_local14, f1_local16["lobbyRoot.lobbyNav"], function ( f40_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f40_arg0:get(),
			modelName = "lobbyRoot.lobbyNav"
		} ) --[[ @ 0]]
	end, false ) --[[ @ 0]]
	AARGameHistory.id = "AARGameHistory" --[[ @ 0]]
	ZmAllTimePerf.id = "ZmAllTimePerf" --[[ @ 0]]
	ZmGenericSummaryList.id = "ZmGenericSummaryList" --[[ @ 0]]
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose ) --[[ @ 0]]
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 ) --[[ @ 0]]
	end
	
	return self
end
 --[[ @ 0]]
CoD.AARSummaryTabInternal.__resetProperties = function ( f41_arg0 )
	f41_arg0.AARScoreWidget:completeAnimation() --[[ @ 0]]
	f41_arg0.AARDamageWidget:completeAnimation() --[[ @ 0]]
	f41_arg0.AAREnemiesKIAWidget:completeAnimation() --[[ @ 0]]
	f41_arg0.AARGameHistory:completeAnimation() --[[ @ 0]]
	f41_arg0.ZmGenericSummaryList:completeAnimation() --[[ @ 0]]
	f41_arg0.ZmAllTimePerf:completeAnimation() --[[ @ 0]]
	f41_arg0.XPMeter:completeAnimation() --[[ @ 0]]
	f41_arg0.PerformanceLabel:completeAnimation() --[[ @ 0]]
	f41_arg0.AARGameInfo:completeAnimation() --[[ @ 0]]
	f41_arg0.ZMPerformanceLabel:completeAnimation() --[[ @ 0]]
	f41_arg0.ZMAARGameInfo:completeAnimation() --[[ @ 0]]
	f41_arg0.AARTierBar:completeAnimation() --[[ @ 0]]
	f41_arg0.AARScoreWidget:setAlpha( 1 ) --[[ @ 0]]
	f41_arg0.AARDamageWidget:setAlpha( 1 ) --[[ @ 0]]
	f41_arg0.AAREnemiesKIAWidget:setAlpha( 1 ) --[[ @ 0]]
	f41_arg0.AARGameHistory:setAlpha( 1 ) --[[ @ 0]]
	f41_arg0.ZmGenericSummaryList:setAlpha( 0 ) --[[ @ 0]]
	f41_arg0.ZmAllTimePerf:setAlpha( 0 ) --[[ @ 0]]
	f41_arg0.XPMeter:setTopBottom( 0, 0, 684, 704 ) --[[ @ 0]]
	f41_arg0.XPMeter:setAlpha( 1 ) --[[ @ 0]]
	f41_arg0.PerformanceLabel:setLeftRight( 0, 0, 638.5, 1493.5 ) --[[ @ 0]]
	f41_arg0.PerformanceLabel:setTopBottom( 0, 0, 91, 129 ) --[[ @ 0]]
	f41_arg0.PerformanceLabel:setAlpha( 1 ) --[[ @ 0]]
	f41_arg0.AARGameInfo:setAlpha( 1 ) --[[ @ 0]]
	f41_arg0.ZMPerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
	f41_arg0.ZMAARGameInfo:setAlpha( 0 ) --[[ @ 0]]
	f41_arg0.AARTierBar:setTopBottom( 0, 0, 732, 752 ) --[[ @ 0]]
	f41_arg0.AARTierBar:setAlpha( 1 ) --[[ @ 0]]
end
 --[[ @ 0]]
CoD.AARSummaryTabInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f42_arg0, f42_arg1 )
			f42_arg0:__resetProperties() --[[ @ 0]]
			f42_arg0:setupElementClipCounter( 0 ) --[[ @ 0]]
		end
	},
	ShowMp_PC = {
		DefaultClip = function ( f43_arg0, f43_arg1 )
			f43_arg0:__resetProperties() --[[ @ 0]]
			f43_arg0:setupElementClipCounter( 12 ) --[[ @ 0]]
			local f43_local0 = function ( f44_arg0 )
				local f44_local0 = function ( f45_arg0 )
					f45_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f45_arg0:setAlpha( 1 ) --[[ @ 0]]
					f45_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.AARTierBar:beginAnimation( 400 ) --[[ @ 0]]
				f43_arg0.AARTierBar:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.AARTierBar:registerEventHandler( "transition_complete_keyframe", f44_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.AARTierBar:completeAnimation() --[[ @ 0]]
			f43_arg0.AARTierBar:setTopBottom( 0, 0, 748, 768 ) --[[ @ 0]]
			f43_arg0.AARTierBar:setAlpha( 0 ) --[[ @ 0]]
			f43_local0( f43_arg0.AARTierBar ) --[[ @ 0]]
			local f43_local1 = function ( f46_arg0 )
				local f46_local0 = function ( f47_arg0 )
					f47_arg0:beginAnimation( 99, Enum[@"luitween"][@"luitween_ease_out"] ) --[[ @ 0]]
					f47_arg0:setAlpha( 1 ) --[[ @ 0]]
					f47_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.XPMeter:beginAnimation( 400 ) --[[ @ 0]]
				f43_arg0.XPMeter:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.XPMeter:registerEventHandler( "transition_complete_keyframe", f46_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.XPMeter:completeAnimation() --[[ @ 0]]
			f43_arg0.XPMeter:setTopBottom( 0, 0, 700, 720 ) --[[ @ 0]]
			f43_arg0.XPMeter:setAlpha( 0 ) --[[ @ 0]]
			f43_local1( f43_arg0.XPMeter ) --[[ @ 0]]
			local f43_local2 = function ( f48_arg0 )
				local f48_local0 = function ( f49_arg0 )
					f49_arg0:beginAnimation( 99, Enum[@"luitween"][@"luitween_ease_out"] ) --[[ @ 0]]
					f49_arg0:setAlpha( 1 ) --[[ @ 0]]
					f49_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.AARGameHistory:beginAnimation( 350 ) --[[ @ 0]]
				f43_arg0.AARGameHistory:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.AARGameHistory:registerEventHandler( "transition_complete_keyframe", f48_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.AARGameHistory:completeAnimation() --[[ @ 0]]
			f43_arg0.AARGameHistory:setAlpha( 0 ) --[[ @ 0]]
			f43_local2( f43_arg0.AARGameHistory ) --[[ @ 0]]
			local f43_local3 = function ( f50_arg0 )
				local f50_local0 = function ( f51_arg0 )
					f51_arg0:beginAnimation( 100 ) --[[ @ 0]]
					f51_arg0:setAlpha( 1 ) --[[ @ 0]]
					f51_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.AAREnemiesKIAWidget:beginAnimation( 210 ) --[[ @ 0]]
				f43_arg0.AAREnemiesKIAWidget:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.AAREnemiesKIAWidget:registerEventHandler( "transition_complete_keyframe", f50_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.AAREnemiesKIAWidget:completeAnimation() --[[ @ 0]]
			f43_arg0.AAREnemiesKIAWidget:setAlpha( 0 ) --[[ @ 0]]
			f43_local3( f43_arg0.AAREnemiesKIAWidget ) --[[ @ 0]]
			local f43_local4 = function ( f52_arg0 )
				local f52_local0 = function ( f53_arg0 )
					f53_arg0:beginAnimation( 100 ) --[[ @ 0]]
					f53_arg0:setAlpha( 1 ) --[[ @ 0]]
					f53_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.AARDamageWidget:beginAnimation( 200 ) --[[ @ 0]]
				f43_arg0.AARDamageWidget:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.AARDamageWidget:registerEventHandler( "transition_complete_keyframe", f52_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.AARDamageWidget:completeAnimation() --[[ @ 0]]
			f43_arg0.AARDamageWidget:setAlpha( 0 ) --[[ @ 0]]
			f43_local4( f43_arg0.AARDamageWidget ) --[[ @ 0]]
			local f43_local5 = function ( f54_arg0 )
				local f54_local0 = function ( f55_arg0 )
					f55_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f55_arg0:setAlpha( 1 ) --[[ @ 0]]
					f55_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.AARScoreWidget:beginAnimation( 190 ) --[[ @ 0]]
				f43_arg0.AARScoreWidget:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.AARScoreWidget:registerEventHandler( "transition_complete_keyframe", f54_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.AARScoreWidget:completeAnimation() --[[ @ 0]]
			f43_arg0.AARScoreWidget:setAlpha( 0 ) --[[ @ 0]]
			f43_local5( f43_arg0.AARScoreWidget ) --[[ @ 0]]
			local f43_local6 = function ( f56_arg0 )
				local f56_local0 = function ( f57_arg0 )
					f57_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f57_arg0:setAlpha( 1 ) --[[ @ 0]]
					f57_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.PerformanceLabel:beginAnimation( 190 ) --[[ @ 0]]
				f43_arg0.PerformanceLabel:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.PerformanceLabel:registerEventHandler( "transition_complete_keyframe", f56_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.PerformanceLabel:completeAnimation() --[[ @ 0]]
			f43_arg0.PerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f43_local6( f43_arg0.PerformanceLabel ) --[[ @ 0]]
			local f43_local7 = function ( f58_arg0 )
				local f58_local0 = function ( f59_arg0 )
					f59_arg0:beginAnimation( 100, Enum[@"luitween"][@"luitween_ease_in"] ) --[[ @ 0]]
					f59_arg0:setAlpha( 1 ) --[[ @ 0]]
					f59_arg0:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f43_arg0.AARGameInfo:beginAnimation( 50 ) --[[ @ 0]]
				f43_arg0.AARGameInfo:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted ) --[[ @ 0]]
				f43_arg0.AARGameInfo:registerEventHandler( "transition_complete_keyframe", f58_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f43_arg0.AARGameInfo:completeAnimation() --[[ @ 0]]
			f43_arg0.AARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f43_local7( f43_arg0.AARGameInfo ) --[[ @ 0]]
			f43_arg0.ZmAllTimePerf:completeAnimation() --[[ @ 0]]
			f43_arg0.ZmAllTimePerf:setAlpha( 0 ) --[[ @ 0]]
			f43_arg0.clipFinished( f43_arg0.ZmAllTimePerf ) --[[ @ 0]]
			f43_arg0.ZmGenericSummaryList:completeAnimation() --[[ @ 0]]
			f43_arg0.ZmGenericSummaryList:setAlpha( 0 ) --[[ @ 0]]
			f43_arg0.clipFinished( f43_arg0.ZmGenericSummaryList ) --[[ @ 0]]
			f43_arg0.ZMPerformanceLabel:completeAnimation() --[[ @ 0]]
			f43_arg0.ZMPerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f43_arg0.clipFinished( f43_arg0.ZMPerformanceLabel ) --[[ @ 0]]
			f43_arg0.ZMAARGameInfo:completeAnimation() --[[ @ 0]]
			f43_arg0.ZMAARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f43_arg0.clipFinished( f43_arg0.ZMAARGameInfo ) --[[ @ 0]]
		end
	},
	ShowZm_PC = {
		DefaultClip = function ( f60_arg0, f60_arg1 )
			f60_arg0:__resetProperties() --[[ @ 0]]
			f60_arg0:setupElementClipCounter( 12 ) --[[ @ 0]]
			f60_arg0.AARTierBar:completeAnimation() --[[ @ 0]]
			f60_arg0.AARTierBar:setTopBottom( 0, 0, 763, 783 ) --[[ @ 0]]
			f60_arg0.AARTierBar:setAlpha( 0 ) --[[ @ 0]]
			f60_arg0.clipFinished( f60_arg0.AARTierBar ) --[[ @ 0]]
			local f60_local0 = function ( f61_arg0 )
				local f61_local0 = function ( f62_arg0 )
					f62_arg0:beginAnimation( 99, Enum[@"luitween"][@"luitween_ease_out"] ) --[[ @ 0]]
					f62_arg0:setAlpha( 1 ) --[[ @ 0]]
					f62_arg0:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f60_arg0.XPMeter:beginAnimation( 400 ) --[[ @ 0]]
				f60_arg0.XPMeter:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted ) --[[ @ 0]]
				f60_arg0.XPMeter:registerEventHandler( "transition_complete_keyframe", f61_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f60_arg0.XPMeter:completeAnimation() --[[ @ 0]]
			f60_arg0.XPMeter:setTopBottom( 0, 0, 720, 740 ) --[[ @ 0]]
			f60_arg0.XPMeter:setAlpha( 0 ) --[[ @ 0]]
			f60_local0( f60_arg0.XPMeter ) --[[ @ 0]]
			f60_arg0.AARGameHistory:completeAnimation() --[[ @ 0]]
			f60_arg0.AARGameHistory:setAlpha( 0 ) --[[ @ 0]]
			f60_arg0.clipFinished( f60_arg0.AARGameHistory ) --[[ @ 0]]
			f60_arg0.AAREnemiesKIAWidget:completeAnimation() --[[ @ 0]]
			f60_arg0.AAREnemiesKIAWidget:setAlpha( 0 ) --[[ @ 0]]
			f60_arg0.clipFinished( f60_arg0.AAREnemiesKIAWidget ) --[[ @ 0]]
			f60_arg0.AARDamageWidget:completeAnimation() --[[ @ 0]]
			f60_arg0.AARDamageWidget:setAlpha( 0 ) --[[ @ 0]]
			f60_arg0.clipFinished( f60_arg0.AARDamageWidget ) --[[ @ 0]]
			f60_arg0.AARScoreWidget:completeAnimation() --[[ @ 0]]
			f60_arg0.AARScoreWidget:setAlpha( 0 ) --[[ @ 0]]
			f60_arg0.clipFinished( f60_arg0.AARScoreWidget ) --[[ @ 0]]
			f60_arg0.PerformanceLabel:completeAnimation() --[[ @ 0]]
			f60_arg0.PerformanceLabel:setLeftRight( 0, 0, 614.5, 1469.5 ) --[[ @ 0]]
			f60_arg0.PerformanceLabel:setTopBottom( 0, 0, 89, 127 ) --[[ @ 0]]
			f60_arg0.PerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f60_arg0.clipFinished( f60_arg0.PerformanceLabel ) --[[ @ 0]]
			f60_arg0.AARGameInfo:completeAnimation() --[[ @ 0]]
			f60_arg0.AARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f60_arg0.clipFinished( f60_arg0.AARGameInfo ) --[[ @ 0]]
			local f60_local1 = function ( f63_arg0 )
				local f63_local0 = function ( f64_arg0 )
					f64_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f64_arg0:setAlpha( 1 ) --[[ @ 0]]
					f64_arg0:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f60_arg0.ZmAllTimePerf:beginAnimation( 350 ) --[[ @ 0]]
				f60_arg0.ZmAllTimePerf:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted ) --[[ @ 0]]
				f60_arg0.ZmAllTimePerf:registerEventHandler( "transition_complete_keyframe", f63_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f60_arg0.ZmAllTimePerf:completeAnimation() --[[ @ 0]]
			f60_arg0.ZmAllTimePerf:setAlpha( 0 ) --[[ @ 0]]
			f60_local1( f60_arg0.ZmAllTimePerf ) --[[ @ 0]]
			local f60_local2 = function ( f65_arg0 )
				local f65_local0 = function ( f66_arg0 )
					f66_arg0:beginAnimation( 100 ) --[[ @ 0]]
					f66_arg0:setAlpha( 1 ) --[[ @ 0]]
					f66_arg0:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f60_arg0.ZmGenericSummaryList:beginAnimation( 200 ) --[[ @ 0]]
				f60_arg0.ZmGenericSummaryList:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted ) --[[ @ 0]]
				f60_arg0.ZmGenericSummaryList:registerEventHandler( "transition_complete_keyframe", f65_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f60_arg0.ZmGenericSummaryList:completeAnimation() --[[ @ 0]]
			f60_arg0.ZmGenericSummaryList:setAlpha( 0 ) --[[ @ 0]]
			f60_local2( f60_arg0.ZmGenericSummaryList ) --[[ @ 0]]
			local f60_local3 = function ( f67_arg0 )
				local f67_local0 = function ( f68_arg0 )
					f68_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f68_arg0:setAlpha( 1 ) --[[ @ 0]]
					f68_arg0:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f60_arg0.ZMPerformanceLabel:beginAnimation( 180 ) --[[ @ 0]]
				f60_arg0.ZMPerformanceLabel:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted ) --[[ @ 0]]
				f60_arg0.ZMPerformanceLabel:registerEventHandler( "transition_complete_keyframe", f67_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f60_arg0.ZMPerformanceLabel:completeAnimation() --[[ @ 0]]
			f60_arg0.ZMPerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f60_local3( f60_arg0.ZMPerformanceLabel ) --[[ @ 0]]
			local f60_local4 = function ( f69_arg0 )
				local f69_local0 = function ( f70_arg0 )
					f70_arg0:beginAnimation( 100, Enum[@"luitween"][@"luitween_ease_in"] ) --[[ @ 0]]
					f70_arg0:setAlpha( 1 ) --[[ @ 0]]
					f70_arg0:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f60_arg0.ZMAARGameInfo:beginAnimation( 50 ) --[[ @ 0]]
				f60_arg0.ZMAARGameInfo:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted ) --[[ @ 0]]
				f60_arg0.ZMAARGameInfo:registerEventHandler( "transition_complete_keyframe", f69_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f60_arg0.ZMAARGameInfo:completeAnimation() --[[ @ 0]]
			f60_arg0.ZMAARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f60_local4( f60_arg0.ZMAARGameInfo ) --[[ @ 0]]
		end
	},
	DefaultState_PC = {
		DefaultClip = function ( f71_arg0, f71_arg1 )
			f71_arg0:__resetProperties() --[[ @ 0]]
			f71_arg0:setupElementClipCounter( 2 ) --[[ @ 0]]
			f71_arg0.AARTierBar:completeAnimation() --[[ @ 0]]
			f71_arg0.AARTierBar:setTopBottom( 0, 0, 748, 768 ) --[[ @ 0]]
			f71_arg0.clipFinished( f71_arg0.AARTierBar ) --[[ @ 0]]
			f71_arg0.XPMeter:completeAnimation() --[[ @ 0]]
			f71_arg0.XPMeter:setTopBottom( 0, 0, 700, 720 ) --[[ @ 0]]
			f71_arg0.clipFinished( f71_arg0.XPMeter ) --[[ @ 0]]
		end
	},
	ShowMp = {
		DefaultClip = function ( f72_arg0, f72_arg1 )
			f72_arg0:__resetProperties() --[[ @ 0]]
			f72_arg0:setupElementClipCounter( 12 ) --[[ @ 0]]
			local f72_local0 = function ( f73_arg0 )
				local f73_local0 = function ( f74_arg0 )
					f74_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f74_arg0:setAlpha( 1 ) --[[ @ 0]]
					f74_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.AARTierBar:beginAnimation( 400 ) --[[ @ 0]]
				f72_arg0.AARTierBar:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.AARTierBar:registerEventHandler( "transition_complete_keyframe", f73_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.AARTierBar:completeAnimation() --[[ @ 0]]
			f72_arg0.AARTierBar:setAlpha( 0 ) --[[ @ 0]]
			f72_local0( f72_arg0.AARTierBar ) --[[ @ 0]]
			local f72_local1 = function ( f75_arg0 )
				local f75_local0 = function ( f76_arg0 )
					f76_arg0:beginAnimation( 99, Enum[@"luitween"][@"luitween_ease_out"] ) --[[ @ 0]]
					f76_arg0:setAlpha( 1 ) --[[ @ 0]]
					f76_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.XPMeter:beginAnimation( 400 ) --[[ @ 0]]
				f72_arg0.XPMeter:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.XPMeter:registerEventHandler( "transition_complete_keyframe", f75_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.XPMeter:completeAnimation() --[[ @ 0]]
			f72_arg0.XPMeter:setAlpha( 0 ) --[[ @ 0]]
			f72_local1( f72_arg0.XPMeter ) --[[ @ 0]]
			local f72_local2 = function ( f77_arg0 )
				local f77_local0 = function ( f78_arg0 )
					f78_arg0:beginAnimation( 99, Enum[@"luitween"][@"luitween_ease_out"] ) --[[ @ 0]]
					f78_arg0:setAlpha( 1 ) --[[ @ 0]]
					f78_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.AARGameHistory:beginAnimation( 350 ) --[[ @ 0]]
				f72_arg0.AARGameHistory:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.AARGameHistory:registerEventHandler( "transition_complete_keyframe", f77_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.AARGameHistory:completeAnimation() --[[ @ 0]]
			f72_arg0.AARGameHistory:setAlpha( 0 ) --[[ @ 0]]
			f72_local2( f72_arg0.AARGameHistory ) --[[ @ 0]]
			local f72_local3 = function ( f79_arg0 )
				local f79_local0 = function ( f80_arg0 )
					f80_arg0:beginAnimation( 100 ) --[[ @ 0]]
					f80_arg0:setAlpha( 1 ) --[[ @ 0]]
					f80_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.AAREnemiesKIAWidget:beginAnimation( 210 ) --[[ @ 0]]
				f72_arg0.AAREnemiesKIAWidget:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.AAREnemiesKIAWidget:registerEventHandler( "transition_complete_keyframe", f79_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.AAREnemiesKIAWidget:completeAnimation() --[[ @ 0]]
			f72_arg0.AAREnemiesKIAWidget:setAlpha( 0 ) --[[ @ 0]]
			f72_local3( f72_arg0.AAREnemiesKIAWidget ) --[[ @ 0]]
			local f72_local4 = function ( f81_arg0 )
				local f81_local0 = function ( f82_arg0 )
					f82_arg0:beginAnimation( 100 ) --[[ @ 0]]
					f82_arg0:setAlpha( 1 ) --[[ @ 0]]
					f82_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.AARDamageWidget:beginAnimation( 200 ) --[[ @ 0]]
				f72_arg0.AARDamageWidget:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.AARDamageWidget:registerEventHandler( "transition_complete_keyframe", f81_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.AARDamageWidget:completeAnimation() --[[ @ 0]]
			f72_arg0.AARDamageWidget:setAlpha( 0 ) --[[ @ 0]]
			f72_local4( f72_arg0.AARDamageWidget ) --[[ @ 0]]
			local f72_local5 = function ( f83_arg0 )
				local f83_local0 = function ( f84_arg0 )
					f84_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f84_arg0:setAlpha( 1 ) --[[ @ 0]]
					f84_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.AARScoreWidget:beginAnimation( 190 ) --[[ @ 0]]
				f72_arg0.AARScoreWidget:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.AARScoreWidget:registerEventHandler( "transition_complete_keyframe", f83_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.AARScoreWidget:completeAnimation() --[[ @ 0]]
			f72_arg0.AARScoreWidget:setAlpha( 0 ) --[[ @ 0]]
			f72_local5( f72_arg0.AARScoreWidget ) --[[ @ 0]]
			local f72_local6 = function ( f85_arg0 )
				local f85_local0 = function ( f86_arg0 )
					f86_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f86_arg0:setAlpha( 1 ) --[[ @ 0]]
					f86_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.PerformanceLabel:beginAnimation( 190 ) --[[ @ 0]]
				f72_arg0.PerformanceLabel:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.PerformanceLabel:registerEventHandler( "transition_complete_keyframe", f85_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.PerformanceLabel:completeAnimation() --[[ @ 0]]
			f72_arg0.PerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f72_local6( f72_arg0.PerformanceLabel ) --[[ @ 0]]
			local f72_local7 = function ( f87_arg0 )
				local f87_local0 = function ( f88_arg0 )
					f88_arg0:beginAnimation( 100, Enum[@"luitween"][@"luitween_ease_in"] ) --[[ @ 0]]
					f88_arg0:setAlpha( 1 ) --[[ @ 0]]
					f88_arg0:registerEventHandler( "transition_complete_keyframe", f72_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f72_arg0.AARGameInfo:beginAnimation( 50 ) --[[ @ 0]]
				f72_arg0.AARGameInfo:registerEventHandler( "interrupted_keyframe", f72_arg0.clipInterrupted ) --[[ @ 0]]
				f72_arg0.AARGameInfo:registerEventHandler( "transition_complete_keyframe", f87_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f72_arg0.AARGameInfo:completeAnimation() --[[ @ 0]]
			f72_arg0.AARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f72_local7( f72_arg0.AARGameInfo ) --[[ @ 0]]
			f72_arg0.ZmAllTimePerf:completeAnimation() --[[ @ 0]]
			f72_arg0.ZmAllTimePerf:setAlpha( 0 ) --[[ @ 0]]
			f72_arg0.clipFinished( f72_arg0.ZmAllTimePerf ) --[[ @ 0]]
			f72_arg0.ZmGenericSummaryList:completeAnimation() --[[ @ 0]]
			f72_arg0.ZmGenericSummaryList:setAlpha( 0 ) --[[ @ 0]]
			f72_arg0.clipFinished( f72_arg0.ZmGenericSummaryList ) --[[ @ 0]]
			f72_arg0.ZMPerformanceLabel:completeAnimation() --[[ @ 0]]
			f72_arg0.ZMPerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f72_arg0.clipFinished( f72_arg0.ZMPerformanceLabel ) --[[ @ 0]]
			f72_arg0.ZMAARGameInfo:completeAnimation() --[[ @ 0]]
			f72_arg0.ZMAARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f72_arg0.clipFinished( f72_arg0.ZMAARGameInfo ) --[[ @ 0]]
		end
	},
	ShowZm = {
		DefaultClip = function ( f89_arg0, f89_arg1 )
			f89_arg0:__resetProperties() --[[ @ 0]]
			f89_arg0:setupElementClipCounter( 12 ) --[[ @ 0]]
			f89_arg0.AARTierBar:completeAnimation() --[[ @ 0]]
			f89_arg0.AARTierBar:setAlpha( 0 ) --[[ @ 0]]
			f89_arg0.clipFinished( f89_arg0.AARTierBar ) --[[ @ 0]]
			local f89_local0 = function ( f90_arg0 )
				local f90_local0 = function ( f91_arg0 )
					f91_arg0:beginAnimation( 99, Enum[@"luitween"][@"luitween_ease_out"] ) --[[ @ 0]]
					f91_arg0:setAlpha( 1 ) --[[ @ 0]]
					f91_arg0:registerEventHandler( "transition_complete_keyframe", f89_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f89_arg0.XPMeter:beginAnimation( 400 ) --[[ @ 0]]
				f89_arg0.XPMeter:registerEventHandler( "interrupted_keyframe", f89_arg0.clipInterrupted ) --[[ @ 0]]
				f89_arg0.XPMeter:registerEventHandler( "transition_complete_keyframe", f90_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f89_arg0.XPMeter:completeAnimation() --[[ @ 0]]
			f89_arg0.XPMeter:setTopBottom( 0, 0, 720, 740 ) --[[ @ 0]]
			f89_arg0.XPMeter:setAlpha( 0 ) --[[ @ 0]]
			f89_local0( f89_arg0.XPMeter ) --[[ @ 0]]
			f89_arg0.AARGameHistory:completeAnimation() --[[ @ 0]]
			f89_arg0.AARGameHistory:setAlpha( 0 ) --[[ @ 0]]
			f89_arg0.clipFinished( f89_arg0.AARGameHistory ) --[[ @ 0]]
			f89_arg0.AAREnemiesKIAWidget:completeAnimation() --[[ @ 0]]
			f89_arg0.AAREnemiesKIAWidget:setAlpha( 0 ) --[[ @ 0]]
			f89_arg0.clipFinished( f89_arg0.AAREnemiesKIAWidget ) --[[ @ 0]]
			f89_arg0.AARDamageWidget:completeAnimation() --[[ @ 0]]
			f89_arg0.AARDamageWidget:setAlpha( 0 ) --[[ @ 0]]
			f89_arg0.clipFinished( f89_arg0.AARDamageWidget ) --[[ @ 0]]
			f89_arg0.AARScoreWidget:completeAnimation() --[[ @ 0]]
			f89_arg0.AARScoreWidget:setAlpha( 0 ) --[[ @ 0]]
			f89_arg0.clipFinished( f89_arg0.AARScoreWidget ) --[[ @ 0]]
			f89_arg0.PerformanceLabel:completeAnimation() --[[ @ 0]]
			f89_arg0.PerformanceLabel:setLeftRight( 0, 0, 614.5, 1469.5 ) --[[ @ 0]]
			f89_arg0.PerformanceLabel:setTopBottom( 0, 0, 89, 127 ) --[[ @ 0]]
			f89_arg0.PerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f89_arg0.clipFinished( f89_arg0.PerformanceLabel ) --[[ @ 0]]
			f89_arg0.AARGameInfo:completeAnimation() --[[ @ 0]]
			f89_arg0.AARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f89_arg0.clipFinished( f89_arg0.AARGameInfo ) --[[ @ 0]]
			local f89_local1 = function ( f92_arg0 )
				local f92_local0 = function ( f93_arg0 )
					f93_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f93_arg0:setAlpha( 1 ) --[[ @ 0]]
					f93_arg0:registerEventHandler( "transition_complete_keyframe", f89_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f89_arg0.ZmAllTimePerf:beginAnimation( 350 ) --[[ @ 0]]
				f89_arg0.ZmAllTimePerf:registerEventHandler( "interrupted_keyframe", f89_arg0.clipInterrupted ) --[[ @ 0]]
				f89_arg0.ZmAllTimePerf:registerEventHandler( "transition_complete_keyframe", f92_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f89_arg0.ZmAllTimePerf:completeAnimation() --[[ @ 0]]
			f89_arg0.ZmAllTimePerf:setAlpha( 0 ) --[[ @ 0]]
			f89_local1( f89_arg0.ZmAllTimePerf ) --[[ @ 0]]
			local f89_local2 = function ( f94_arg0 )
				local f94_local0 = function ( f95_arg0 )
					f95_arg0:beginAnimation( 100 ) --[[ @ 0]]
					f95_arg0:setAlpha( 1 ) --[[ @ 0]]
					f95_arg0:registerEventHandler( "transition_complete_keyframe", f89_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f89_arg0.ZmGenericSummaryList:beginAnimation( 200 ) --[[ @ 0]]
				f89_arg0.ZmGenericSummaryList:registerEventHandler( "interrupted_keyframe", f89_arg0.clipInterrupted ) --[[ @ 0]]
				f89_arg0.ZmGenericSummaryList:registerEventHandler( "transition_complete_keyframe", f94_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f89_arg0.ZmGenericSummaryList:completeAnimation() --[[ @ 0]]
			f89_arg0.ZmGenericSummaryList:setAlpha( 0 ) --[[ @ 0]]
			f89_local2( f89_arg0.ZmGenericSummaryList ) --[[ @ 0]]
			local f89_local3 = function ( f96_arg0 )
				local f96_local0 = function ( f97_arg0 )
					f97_arg0:beginAnimation( 99 ) --[[ @ 0]]
					f97_arg0:setAlpha( 1 ) --[[ @ 0]]
					f97_arg0:registerEventHandler( "transition_complete_keyframe", f89_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f89_arg0.ZMPerformanceLabel:beginAnimation( 180 ) --[[ @ 0]]
				f89_arg0.ZMPerformanceLabel:registerEventHandler( "interrupted_keyframe", f89_arg0.clipInterrupted ) --[[ @ 0]]
				f89_arg0.ZMPerformanceLabel:registerEventHandler( "transition_complete_keyframe", f96_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f89_arg0.ZMPerformanceLabel:completeAnimation() --[[ @ 0]]
			f89_arg0.ZMPerformanceLabel:setAlpha( 0 ) --[[ @ 0]]
			f89_local3( f89_arg0.ZMPerformanceLabel ) --[[ @ 0]]
			local f89_local4 = function ( f98_arg0 )
				local f98_local0 = function ( f99_arg0 )
					f99_arg0:beginAnimation( 100, Enum[@"luitween"][@"luitween_ease_in"] ) --[[ @ 0]]
					f99_arg0:setAlpha( 1 ) --[[ @ 0]]
					f99_arg0:registerEventHandler( "transition_complete_keyframe", f89_arg0.clipFinished ) --[[ @ 0]]
				end
				 --[[ @ 0]]
				f89_arg0.ZMAARGameInfo:beginAnimation( 50 ) --[[ @ 0]]
				f89_arg0.ZMAARGameInfo:registerEventHandler( "interrupted_keyframe", f89_arg0.clipInterrupted ) --[[ @ 0]]
				f89_arg0.ZMAARGameInfo:registerEventHandler( "transition_complete_keyframe", f98_local0 ) --[[ @ 0]]
			end
			 --[[ @ 0]]
			f89_arg0.ZMAARGameInfo:completeAnimation() --[[ @ 0]]
			f89_arg0.ZMAARGameInfo:setAlpha( 0 ) --[[ @ 0]]
			f89_local4( f89_arg0.ZMAARGameInfo ) --[[ @ 0]]
		end
	}
} --[[ @ 0]]
CoD.AARSummaryTabInternal.__onClose = function ( f100_arg0 )
	f100_arg0.AARTierBar:close() --[[ @ 0]]
	f100_arg0.XPMeter:close() --[[ @ 0]]
	f100_arg0.AARGameHistory:close() --[[ @ 0]]
	f100_arg0.AAREnemiesKIAWidget:close() --[[ @ 0]]
	f100_arg0.AARDamageWidget:close() --[[ @ 0]]
	f100_arg0.AARScoreWidget:close() --[[ @ 0]]
	f100_arg0.AARGameInfo:close() --[[ @ 0]]
	f100_arg0.ZmAllTimePerf:close() --[[ @ 0]]
	f100_arg0.ZmGenericSummaryList:close() --[[ @ 0]]
	f100_arg0.ZMAARGameInfo:close() --[[ @ 0]]
	f100_arg0.LootCaseMeter:close() --[[ @ 0]]
end
 --[[ @ 0]]
